// js/auth.session.manager.js - Session manager with server-enforced inactivity timeout
(function () {
    'use strict';
    const CONFIG={SESSION_KEY:'kynecta_session',ACCOUNTS_KEY:'kynecta_saved_accounts',MAX_ACCOUNTS_PER_DEVICE:2,SESSION_DURATION_DAYS:30,CHECK_INTERVAL:60000,STORAGE_VERSION:'1.3.0',ACTIVITY_THROTTLE_MS:5000};
    let currentSession=null,savedAccounts=[],sessionCheckInterval=null,lastActivityTime=Date.now(),lastSaveTime=0,savePending=false,lastActivityCallTime=0,refreshInProgress=false,refreshTransient=false,initialized=false;
    function decodeJwtPayload(token){try{if(!token||typeof token!=='string')return null;const p=token.split('.');if(p.length!==3)return null;const n=p[1].replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(atob(n+'='.repeat((4-n.length%4)%4)));}catch(_){return null;}}
    function getTokenExpiry(token){const p=decodeJwtPayload(token);return p&&Number.isFinite(p.exp)?p.exp*1000:null;}
    function localTimeoutOff(){try{return window.AppSettings&&typeof window.AppSettings.get==='function'&&window.AppSettings.get('security.sessionTimeout')==='off';}catch(_){return false;}}
    // FIX (OFF-BECAME-30-DAYS): sessionTimeoutMs === 0 means the user chose "Off" (never time out). This used to fall through to the 30-day default.
    // Returns 0 for "never". Token claim wins (server truth); only tokens without the claim fall back to the local Off setting.
    function getSessionTimeoutMs(tokenOrSession){const token=typeof tokenOrSession==='string'?tokenOrSession:tokenOrSession&&tokenOrSession.token,p=decodeJwtPayload(token);if(p&&Number.isFinite(p.sessionTimeoutMs))return p.sessionTimeoutMs>0?p.sessionTimeoutMs:0;return localTimeoutOff()?0:CONFIG.SESSION_DURATION_DAYS*86400000;}
    function isInactiveTooLong(s){const timeout=getSessionTimeoutMs(s);if(!(timeout>0))return false;const last=Number(s&&s.lastActivity)||Number(s&&s.createdAt)||Date.now();return Date.now()-last>=timeout;}
    function getStoredRefreshToken(session){if(session?.refreshToken)return session.refreshToken;try{const a=JSON.parse(localStorage.getItem('kynecta_auth')||'{}');if(a.refreshToken)return a.refreshToken;}catch(_){}return localStorage.getItem('REFRESH_TOKEN')||localStorage.getItem('refreshToken')||null;}
    function getSessionExpiry(session){return getTokenExpiry(getStoredRefreshToken(session))||getTokenExpiry(session?.token)||null;}
    function isTokenValid(token){const p=decodeJwtPayload(token);return !!p&&(!p.exp||p.exp*1000>Date.now());}
    function clearSession(){currentSession=null;try{localStorage.removeItem(CONFIG.SESSION_KEY);}catch(_){}lastSaveTime=0;savePending=false;}
    function loadSession(){try{const raw=localStorage.getItem(CONFIG.SESSION_KEY);if(!raw)return null;const s=JSON.parse(raw);if(!s||typeof s!=='object'||!s.token||!s.userId){clearSession();return null;}currentSession=s;lastActivityTime=Number(s.lastActivity)||Date.now();if(!window.currentUser&&s.user)window.currentUser=s.user;return s;}catch(e){console.warn('[SessionManager] Failed to load session:',e.message);return null;}}
    function performSaveSession(){try{if(!currentSession){localStorage.removeItem(CONFIG.SESSION_KEY);return true;}localStorage.setItem(CONFIG.SESSION_KEY,JSON.stringify({...currentSession,lastActivity:lastActivityTime,version:CONFIG.STORAGE_VERSION,expiresAt:getSessionExpiry(currentSession)||Date.now()+getSessionTimeoutMs(currentSession)}));lastSaveTime=Date.now();return true;}catch(e){console.error('[SessionManager] Failed to save session:',e);return false;}}
    function debouncedSaveSession(){if(savePending)return;const now=Date.now();if(now-lastSaveTime<CONFIG.ACTIVITY_THROTTLE_MS){savePending=true;setTimeout(()=>{savePending=false;if(currentSession)performSaveSession();},CONFIG.ACTIVITY_THROTTLE_MS-(now-lastSaveTime));return;}performSaveSession();}
    function saveSession(){debouncedSaveSession();}
    function updateActivity(){const now=Date.now();if(now-lastActivityCallTime<CONFIG.ACTIVITY_THROTTLE_MS)return;lastActivityCallTime=now;lastActivityTime=now;if(currentSession){currentSession.lastActivity=now;saveSession();}}
    function setupActivityTracking(){['click','keypress','scroll','touchstart','mousemove'].forEach(e=>window.addEventListener(e,updateActivity,{passive:true}));}
    function loadSavedAccounts(){try{const raw=localStorage.getItem(CONFIG.ACCOUNTS_KEY);savedAccounts=raw?JSON.parse(raw):[];if(!Array.isArray(savedAccounts))savedAccounts=[];}catch(_){savedAccounts=[];}return savedAccounts;}
    function saveAccounts(){try{localStorage.setItem(CONFIG.ACCOUNTS_KEY,JSON.stringify(savedAccounts));return true;}catch(_){return false;}}
    function addAccount(userData,token){loadSavedAccounts();const i=savedAccounts.findIndex(a=>a.userId===userData.id||a.email===userData.email),r={userId:userData.id,email:userData.email,username:userData.username,displayName:userData.displayName||userData.username,avatar:userData.avatar,token,lastUsed:Date.now()};if(i>=0)savedAccounts[i]={...savedAccounts[i],...r};else{if(savedAccounts.length>=CONFIG.MAX_ACCOUNTS_PER_DEVICE)return{success:false,error:`Maximum ${CONFIG.MAX_ACCOUNTS_PER_DEVICE} accounts per device`};savedAccounts.push({...r,createdAt:Date.now()});}saveAccounts();return{success:true};}
    function removeAccount(userId){loadSavedAccounts();const before=savedAccounts.length;savedAccounts=savedAccounts.filter(a=>a.userId!==userId);if(before!==savedAccounts.length){saveAccounts();if(currentSession?.userId===userId)clearSession();return true;}return false;}
    function getSavedAccounts(){loadSavedAccounts();return savedAccounts.map(a=>({userId:a.userId,email:a.email,username:a.username,displayName:a.displayName,avatar:a.avatar,lastUsed:a.lastUsed}));}
    function createSession(userData,token,rememberMe=true){if(!rememberMe)return{success:true,ephemeral:true};currentSession={userId:userData.id||userData.userId,email:userData.email,username:userData.username,displayName:userData.displayName||userData.username,avatar:userData.avatar,token,user:userData,createdAt:Date.now(),lastActivity:Date.now()};lastActivityTime=Date.now();lastSaveTime=0;performSaveSession();return{success:true,accountResult:addAccount(userData,token)};}
    function destroySession(){clearSession();return{success:true};}
    async function logout(keepAccount=false){try{if(window.api?.auth?.logout)await window.api.auth.logout();}catch(e){console.warn('[SessionManager] Logout API call failed:',e.message);}const id=currentSession?.userId;destroySession();['token','accessToken','necpa_token','USER_TOKEN','currentUser','user','kynecta_auth'].forEach(k=>{try{localStorage.removeItem(k);}catch(_){}});window.currentUser=null;if(!keepAccount&&id)removeAccount(id);if(location.pathname.includes('chat.html'))setTimeout(()=>{location.href='index.html';},500);return{success:true};}
    function shouldPromptLogin(explicitSession){const s=explicitSession||loadSession();if(!s)return true;if(isInactiveTooLong(s)){clearSession();return true;}return false;}
    async function _attemptTokenRefresh(session){refreshTransient=false;if(refreshInProgress){refreshTransient=true;return false;}refreshInProgress=true;try{if(window.api?.auth?.refreshToken){const r=await window.api.auth.refreshToken();if(r&&r.success!==false)return true;}const refresh=getStoredRefreshToken(session);if(!refresh)return false;const origin=typeof window.__getApiOrigin==='function'?window.__getApiOrigin():'';if(!origin){console.error('[SessionManager] Cannot refresh token: BACKEND_URL is not configured.');return false;}const response=await fetch(`${origin.replace(/\/+$/,'')}/api/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken:refresh}),credentials:'include'});if(!response.ok){/* FIX: only a definite 401/403 means the refresh token is dead; 5xx/429/408 (cold start, overload) are retryable and must not log the user out */refreshTransient=!(response.status===401||response.status===403||response.status===404);return false;}const data=await response.json();const newToken=data.token||data.accessToken;if(!data.success||!newToken)return false;const newRefresh=data.refreshToken||refresh;['authToken','accessToken','token','necpa_token','USER_TOKEN','kynecta_token','auth_token'].forEach(k=>{try{localStorage.removeItem(k);}catch(_){}});currentSession={...session,token:newToken,refreshToken:newRefresh,lastActivity:Date.now()};lastActivityTime=Date.now();lastSaveTime=0;performSaveSession();const authPayload={token:newToken,refreshToken:newRefresh,user:session.user,expiresAt:getTokenExpiry(newRefresh)||getTokenExpiry(newToken)||Date.now()+getSessionTimeoutMs(newToken),issuedAt:Date.now()};if(window.AuthStorage?.saveAuth)window.AuthStorage.saveAuth(authPayload);else localStorage.setItem('kynecta_auth',JSON.stringify(authPayload));['authToken','accessToken','token','necpa_token','USER_TOKEN','kynecta_token'].forEach(k=>{try{localStorage.setItem(k,newToken);}catch(_){}});['REFRESH_TOKEN','refreshToken'].forEach(k=>{try{localStorage.setItem(k,newRefresh);}catch(_){}});window.__userToken=newToken;window.__accessToken=newToken;if(window.__SESSION__){window.__SESSION__.token=newToken;window.__SESSION__.refreshToken=newRefresh;}window.dispatchEvent(new CustomEvent('auth:token:refreshed',{detail:{token:newToken,timestamp:Date.now()}}));window.dispatchEvent(new CustomEvent('session:restored',{detail:{token:newToken,user:session.user,timestamp:Date.now()}}));return true;}catch(e){console.error('[SessionManager] Refresh error:',e.message);refreshTransient=true;return false;}finally{refreshInProgress=false;}}
    // true = refreshed, or failed for a reason that may pass (offline, server waking up, another refresh in flight): keep the session.
    async function _refreshOrKeep(s){const ok=await _attemptTokenRefresh(s);return ok||refreshTransient;}
    function endSession(reason){clearSession();try{window.dispatchEvent(new CustomEvent('auth:session:ended',{detail:{reason,timestamp:Date.now()}}));}catch(_){} }
    function startSessionCheck(){if(sessionCheckInterval)clearInterval(sessionCheckInterval);sessionCheckInterval=setInterval(async()=>{const s=loadSession();if(!s?.token)return;if(isInactiveTooLong(s)){endSession('inactivity_timeout');return;}if(!isTokenValid(s.token)&&!(await _refreshOrKeep(s)))endSession('refresh_failed');},CONFIG.CHECK_INTERVAL);if(!window.__SESSION_MANAGER_ONLINE_LISTENER__){window.__SESSION_MANAGER_ONLINE_LISTENER__=true;window.addEventListener('online',async()=>{const s=loadSession();if(!s?.token)return;if(isInactiveTooLong(s)){endSession('inactivity_timeout');return;}if(!isTokenValid(s.token))await _attemptTokenRefresh(s);});}}
    async function performAutoLogin(){const s=loadSession();if(!s)return{success:false,reason:'no_session'};if(isInactiveTooLong(s)){endSession('inactivity_timeout');return{success:false,reason:'inactivity_timeout'};}if(!isTokenValid(s.token)&&!(await _refreshOrKeep(s))){endSession('refresh_failed');return{success:false,reason:'invalid_token'};}const restored=loadSession();if(!restored?.user)return{success:false,reason:'no_user_in_session'};window.currentUser=restored.user;return{success:true,user:restored.user,token:restored.token};}
    async function initialize(){if(initialized)return{success:true};initialized=true;loadSavedAccounts();setupActivityTracking();let explicit=null;try{const auth=JSON.parse(localStorage.getItem('kynecta_auth')||'{}');if(auth?.token&&auth?.user?.id){explicit={...auth,userId:auth.user.id,token:auth.token,lastActivity:Number(auth.lastActivity)||Date.now()};currentSession=explicit;lastActivityTime=explicit.lastActivity;}}catch(_){}if(explicit&&isTokenValid(explicit.token))performSaveSession();startSessionCheck();return{success:true,session:currentSession};}
    window.AuthSessionManager={initialize,loadSession,createSession,destroySession,logout,shouldPromptLogin,getSavedAccounts,addAccount,removeAccount,performAutoLogin,refreshToken:()=>_attemptTokenRefresh(currentSession||loadSession()),getCurrentSession:()=>currentSession,isTokenValid};
    try{initialize();}catch(e){console.error('[SessionManager] Initialization failed:',e);}
})();
