// js/config.js - single runtime configuration gateway
(function () {
'use strict';
const runtime=window.__NEXIPA_RUNTIME_CONFIG__||{};
const configuredOrigin=String(runtime.BACKEND_URL||'').trim().replace(/\/+$/,'');
if(!configuredOrigin)console.error('[Config] BACKEND_URL is missing. Run the frontend build and configure it in .env.');
function requireBackendOrigin(){if(!configuredOrigin)throw new Error('BACKEND_URL is not configured. Set BACKEND_URL in .env and rebuild the frontend.');return configuredOrigin;}
window.__isLocalEnvironment=window.__isLocalEnvironment||function(hostname){const host=String(hostname||window.location.hostname||'').toLowerCase();if(!host)return true;if(host==='localhost'||host==='127.0.0.1'||host==='0.0.0.0')return true;if(host.endsWith('.local'))return true;if(host.startsWith('192.168.')||host.startsWith('10.'))return true;return /^172\.(1[6-9]|2\d|3[0-1])\./.test(host);};
window.__isProductionConsoleHost=window.__isProductionConsoleHost||function(){const host=String(window.location?.hostname||'').toLowerCase();return !!host&&!window.__isLocalEnvironment(host);};
window.__getApiOrigin=()=>requireBackendOrigin();window.__getApiBase=()=>`${requireBackendOrigin()}/api`;window.BACKEND_URL=configuredOrigin;window.GOOGLE_CLIENT_ID=String(runtime.GOOGLE_CLIENT_ID||'').trim();window.FRONTEND_URL=String(runtime.FRONTEND_URL||'').trim().replace(/\/+$/,'');window.NECPRA_APP_NAME='Necpra';window.NECPRA_APP_SHORT_NAME='Necpra';
function normalizeBrandText(v){if(typeof v!=='string'||!v)return v;return v.replace(/Kynecta/gi,'Necpra').replace(/Knecta/gi,'Necpra').replace(/MoodChat/gi,'Necpra').replace(/Mood Chat/gi,'Necpra').replace(/Necpa/gi,'Necpra');}
function applyNecpraBrand(root){const target=root||document;if(!target)return;if(target.nodeType===Node.TEXT_NODE){const n=normalizeBrandText(target.nodeValue);if(n!==target.nodeValue)target.nodeValue=n;return;}if(target.nodeType!==Node.ELEMENT_NODE&&target!==document)return;if(target===document){if(document.title)document.title=normalizeBrandText(document.title);}else if(target.tagName==='TITLE')target.textContent=normalizeBrandText(target.textContent);const walker=document.createTreeWalker(target,NodeFilter.SHOW_TEXT);const nodes=[];let node;while((node=walker.nextNode()))nodes.push(node);nodes.forEach(n=>{const x=normalizeBrandText(n.nodeValue);if(x!==n.nodeValue)n.nodeValue=x;});}
function initializeNecpraBranding(){try{document.documentElement.setAttribute('data-app-brand','necpra');applyNecpraBrand(document);if(window.MutationObserver&&document.documentElement)new MutationObserver(ms=>ms.forEach(m=>m.addedNodes&&m.addedNodes.forEach(n=>{if(n.nodeType===Node.ELEMENT_NODE||n.nodeType===Node.TEXT_NODE)applyNecpraBrand(n);}))).observe(document.documentElement,{childList:true,subtree:true});}catch(_) {}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initializeNecpraBranding,{once:true});else initializeNecpraBranding();
function isBackendApiPath(url){try{const p=new URL(url,window.location.origin);return /^\/api(?:\/|$)/i.test(p.pathname)||/^\/socket\.io(?:\/|$)/i.test(p.pathname)||/^\/ws(?:\/|$)/i.test(p.pathname);}catch(_){return false;}}
window.__rewriteApiUrl=function(input){const apiOrigin=requireBackendOrigin();const normalize=raw=>{if(!raw||typeof raw!=='string')return raw;if(/^\/api(?:\/|$)/i.test(raw)||/^\/socket\.io(?:\/|$)/i.test(raw)||/^\/ws(?:\/|$)/i.test(raw))return `${apiOrigin}${raw}`;try{const p=new URL(raw,window.location.origin);if(isBackendApiPath(p.href))return `${apiOrigin}${p.pathname}${p.search}${p.hash}`;}catch(_){}return raw;};if(typeof Request!=='undefined'&&input instanceof Request){const u=normalize(input.url);return u===input.url?input:new Request(u,input);}return normalize(input);};
if(!window.__KYNECTA_API_FETCH_PATCHED__&&typeof window.fetch==='function'){window.__KYNECTA_API_FETCH_PATCHED__=true;const nativeFetch=window.fetch.bind(window);window.fetch=(input,init)=>nativeFetch(window.__rewriteApiUrl(input),init);}
if(!window.__KYNECTA_API_XHR_PATCHED__&&typeof XMLHttpRequest!=='undefined'){window.__KYNECTA_API_XHR_PATCHED__=true;const nativeOpen=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(method,url){return nativeOpen.apply(this,[method,window.__rewriteApiUrl(url)].concat([].slice.call(arguments,2)));};}
if(!window.__KYNECTA_WEBSOCKET_PATCHED__&&typeof window.WebSocket==='function'){window.__KYNECTA_WEBSOCKET_PATCHED__=true;const NativeWebSocket=window.WebSocket;const ConfiguredWebSocket=function(url,protocols){let target=url;try{const p=new URL(url,window.location.origin);if(/^\/socket\.io(?:\/|$)/i.test(p.pathname)||/^\/ws(?:\/|$)/i.test(p.pathname)){const api=new URL(requireBackendOrigin());p.protocol=api.protocol==='https:'?'wss:':'ws:';p.host=api.host;target=p.toString();}}catch(_){}return protocols===undefined?new NativeWebSocket(target):new NativeWebSocket(target,protocols);};ConfiguredWebSocket.prototype=NativeWebSocket.prototype;window.WebSocket=ConfiguredWebSocket;}
window.apiCall=async function(endpoint,options){const url=`${window.__getApiBase()}${String(endpoint||'').startsWith('/')?endpoint:`/${endpoint||''}`}`;const final=Object.assign({headers:{'Content-Type':'application/json'}},options||{});final.headers=Object.assign({'Content-Type':'application/json'},options?.headers||{});const t=localStorage.getItem('authToken')||localStorage.getItem('accessToken')||localStorage.getItem('token');if(t&&!final.headers.Authorization)final.headers.Authorization=`Bearer ${t}`;try{const r=await fetch(url,final);return await r.json().catch(()=>({}));}catch(e){console.error('[API] Request failed:',e);return{success:false,message:e.message};}};
if(!Object.getOwnPropertyDescriptor(window,'authToken')||Object.getOwnPropertyDescriptor(window,'authToken').configurable){let legacy=null;try{const d=Object.getOwnPropertyDescriptor(window,'authToken');if(d&&'value'in d)legacy=d.value;}catch(_){}try{Object.defineProperty(window,'authToken',{configurable:true,enumerable:true,get(){try{if(window.__kynToken)return window.__kynToken;}catch(_){}try{if(window.__accessToken)return window.__accessToken;}catch(_){}try{if(window.AuthSessionManager?.getToken){const t=window.AuthSessionManager.getToken();if(t)return t;}}catch(_){}for(const k of ['authToken','accessToken','token','jwt','USER_TOKEN','necpa_token']){try{const t=localStorage.getItem(k)||sessionStorage.getItem(k);if(t&&!t.startsWith('{'))return t;}catch(_){} }return legacy||'';},set(v){legacy=v||null;}});}catch(_){} }
if(/\/message\.html$/i.test(window.location.pathname)&&!document.querySelector('script[data-group-message-isolation]')){const s=document.createElement('script');s.src='/js/group-message-isolation.js';s.async=false;s.dataset.groupMessageIsolation='true';(document.head||document.documentElement).appendChild(s);}
if(/\/group\.html$/i.test(window.location.pathname)&&!document.querySelector('script[data-group-panel-cleanup]')){const s=document.createElement('script');s.src='/js/group-panel-cleanup.js';s.async=false;s.dataset.groupPanelCleanup='true';(document.head||document.documentElement).appendChild(s);}
console.log('[Config] Runtime configuration loaded. Backend:',configuredOrigin||'(missing)');
})();
