/**
 * Group-only E2E key lifecycle.
 * Exact-version key fetch/retry; reading history never rotates the group key.
 */
(function(global){
'use strict';
const cache=new Map(), inflight=new Map(), stateInflight=new Map();
const base=()=>String(global.__getApiBase?.()||global.API_BASE_URL||'').replace(/\/$/,'');
const token=()=>global.__kynToken||global.__accessToken||global.AuthSessionManager?.getToken?.()||global.authToken||localStorage.getItem('authToken')||localStorage.getItem('accessToken')||localStorage.getItem('token')||'';
const me=()=>Number(global._kynCurrentUserId||localStorage.getItem('userId')||localStorage.getItem('currentUserId')||0);
function e2e(){if(!global.KynectaE2E)throw new Error('Secure messaging core is not loaded');return global.KynectaE2E}
async function request(path,opts){opts=opts||{};const headers=Object.assign({},opts.headers||{}),t=token();if(t)headers.Authorization='Bearer '+t;if(opts.body&&!headers['Content-Type'])headers['Content-Type']='application/json';let res=await fetch(base()+path,Object.assign({},opts,{headers}));if(res.status===401&&global.NecpaSessionResilience){try{if(await global.NecpaSessionResilience.refreshAccessToken(base())){const fresh=token();if(fresh)headers.Authorization='Bearer '+fresh;res=await fetch(base()+path,Object.assign({},opts,{headers}))}}catch(_){}}const data=await res.json().catch(()=>({}));if(!res.ok){const err=new Error(data.message||data.error||('Request failed ('+res.status+')'));err.status=res.status;err.payload=data;throw err}return data}
async function waitReady(timeout=20000){if(global.KynectaE2E?.enabled)return true;if(typeof global.__NECPRA_ENSURE_E2E==='function'){try{await global.__NECPRA_ENSURE_E2E()}catch(_){}}const started=Date.now();while(!global.KynectaE2E?.enabled&&Date.now()-started<timeout)await new Promise(r=>setTimeout(r,150));return!!global.KynectaE2E?.enabled}
function bucket(gid){const id=String(gid);if(!cache.has(id))cache.set(id,new Map());return cache.get(id)}
function storageKey(gid,v){return'kyn_group_key_v2_'+gid+'_'+v}
async function saveLocal(gid,v,rawB64,ownerId){try{const wrapped=await e2e().wrapForLocalStorage(rawB64);if(wrapped)localStorage.setItem(storageKey(gid,v),JSON.stringify({ownerId:Number(ownerId)||0,wrapped}))}catch(_){}}
async function loadLocal(gid,v){try{const raw=localStorage.getItem(storageKey(gid,v));if(!raw)return null;const obj=JSON.parse(raw),wrapped=obj?.wrapped||raw,rawB64=await e2e().unwrapFromLocalStorage(wrapped);return{key:await e2e().importSenderKey(rawB64),ownerId:Number(obj?.ownerId)||0}}catch(_){return null}}
async function fetchState(gid,force){const id=String(gid);if(!force&&stateInflight.has(id))return stateInflight.get(id);const p=request('/group-encryption/'+encodeURIComponent(id)+'/state').then(r=>r.data||{});stateInflight.set(id,p);try{return await p}finally{if(stateInflight.get(id)===p)stateInflight.delete(id)}}
function entryFor(state,v){v=Number(v);if(Number(state?.version)===v)return{version:v,ownerId:Number(state?.lastEvent?.actorId)||0,distributions:Array.isArray(state?.distributions)?state.distributions:[]};const hit=(Array.isArray(state?.history)?state.history:[]).find(x=>Number(x?.version)===v);if(!hit)return null;return{version:v,ownerId:Number(hit.actorId)||0,distributions:Array.isArray(hit.distributions)?hit.distributions:[]}}
async function installVersion(gid,state,v){v=Number(v);if(!Number.isInteger(v)||v<1)return null;const local=bucket(gid).get(v);if(local)return local;const persisted=await loadLocal(gid,v);if(persisted?.key){const installed={version:v,key:persisted.key,ownerId:persisted.ownerId||Number(entryFor(state,v)?.ownerId)||0};bucket(gid).set(v,installed);return installed}const entry=entryFor(state,v);if(!entry?.ownerId)return null;const mine=entry.distributions.find(d=>String(d?.userId)===String(me()));if(!mine?.ciphertext)return null;const rawB64=await e2e().decryptSenderKeyFrom(mine.ciphertext,entry.ownerId),installed={version:v,key:await e2e().importSenderKey(rawB64),ownerId:entry.ownerId};bucket(gid).set(v,installed);await saveLocal(gid,v,rawB64,entry.ownerId);return installed}
async function resolveMembers(gid,hint){let ids=Array.isArray(hint)?hint.map(Number):[];ids=ids.filter(Number.isInteger).filter(n=>n>0);if(!ids.length){try{const r=await request('/chats/'+encodeURIComponent(gid)),chat=r?.data?.chat||r?.data||{},list=Array.isArray(chat.participants)?chat.participants:[];ids=list.map(p=>Number((p?.user||p)?.id??p?.userId)).filter(Number.isInteger).filter(n=>n>0)}catch(_){}}ids=[...new Set(ids)];if(!ids.includes(me()))ids.push(me());return ids}
async function rotate(gid,hint,state){const ids=await resolveMembers(gid,hint);if(!ids.length)throw new Error('Could not resolve group members for key distribution');const generated=await e2e().generateSenderKey(),distributions=[];for(const userId of ids){try{const ciphertext=await e2e().encryptSenderKeyFor(generated.rawB64,userId);distributions.push({userId,deviceId:'primary',ciphertext,algorithm:'SenderKey-ECDH-P256-AES256GCM-v1'})}catch(err){console.warn('[GroupE2E] key distribution skipped for member',userId,err?.message)}}if(!distributions.some(d=>String(d.userId)===String(me())))throw new Error('Your group encryption identity is not ready');const version=Number(state?.version||0)+1;let result;try{result=await request('/group-encryption/'+encodeURIComponent(gid)+'/rotate',{method:'POST',body:JSON.stringify({version,algorithm:'SenderKey-ECDH-P256-AES256GCM-v1',distributions,reason:state?.reason||'initial_key'})})}catch(err){if(err.status===409){const fresh=await fetchState(gid,true),existing=await installVersion(gid,fresh,Number(fresh.version));if(existing)return existing}throw err}const data=result?.data||{},installed={version:Number(data.version||version),key:generated.key,ownerId:me()};bucket(gid).set(installed.version,installed);await saveLocal(gid,installed.version,generated.rawB64,me());try{await request('/group-encryption/'+encodeURIComponent(gid)+'/ack',{method:'POST',body:JSON.stringify({version:installed.version,deviceId:'primary'})})}catch(_){}return installed}
async function ensureCurrentKey(gid,hint){const id=String(gid);if(inflight.has(id))return inflight.get(id);const p=(async()=>{if(!(await waitReady()))throw new Error('Secure group messaging is not ready yet');const state=await fetchState(id,true),current=Number(state.version||0);if(current>0&&!state.pendingRotation){const installed=await installVersion(id,state,current);if(installed)return installed}return rotate(id,hint,state)})();inflight.set(id,p);try{return await p}finally{if(inflight.get(id)===p)inflight.delete(id)}}
async function encryptForGroup(gid,plaintext,hint){const installed=await ensureCurrentKey(gid,hint),env=JSON.parse(await e2e().encryptGroupMessage(plaintext,installed.key,installed.version));env.owner=Number(installed.ownerId||me());env.group=String(gid);return JSON.stringify(env)}
async function decryptForGroup(gid,ciphertext){if(!ciphertext||typeof ciphertext!=='string')return ciphertext;let envelope;try{envelope=JSON.parse(ciphertext)}catch(_){return ciphertext}if(!envelope||envelope.v!==1||!Number.isInteger(Number(envelope.gen)))return ciphertext;if(!(await waitReady()))throw new Error('Secure group messaging is not ready yet');const version=Number(envelope.gen);let state=await fetchState(gid,false),installed=await installVersion(gid,state,version);if(!installed){state=await fetchState(gid,true);installed=await installVersion(gid,state,version)}if(!installed)throw new Error('Group key version '+version+' is not available for this member');let plain=await e2e().decryptGroupMessage(ciphertext,installed.key);if(plain==='[Decryption failed]'){bucket(gid).delete(version);state=await fetchState(gid,true);installed=await installVersion(gid,state,version);if(installed)plain=await e2e().decryptGroupMessage(ciphertext,installed.key)}if(plain==='[Decryption failed]')throw new Error('Group ciphertext authentication failed');return plain}
async function rotateSenderKey(gid,hint){bucket(String(gid)).clear();return ensureCurrentKey(String(gid),hint)}
global.KynectaGroupE2E={ensureGroupKey:ensureCurrentKey,encryptForGroup,decryptForGroup,rotateSenderKey};
console.log('[KynectaGroupE2E] Loaded — exact-version group key fetch/retry active')
})(window);
