(() => {
  'use strict';
  const state={active:false,callId:null,chatId:null,type:'audio',room:null,localStream:null,peers:new Map(),cursor:0,pollTimer:null,currentUserId:'',root:null,grid:null,status:null};
  const apiBase=()=>{const b=typeof window.__getApiBase==='function'?window.__getApiBase():(window.API_BASE_URL||'');return String(b).replace(/\/$/,'')+'/group-calls'};
  // Use the same canonical session/token sources as the rest of the app. The
  // old implementation only checked three legacy localStorage keys, which
  // meant a valid kynecta_session could still produce a 401 on production
  // group-call signaling/join requests.
  const token=()=>{
    try { if (window.__kynToken) return String(window.__kynToken); } catch (_) {}
    try { if (window.__accessToken) return String(window.__accessToken); } catch (_) {}
    try { if (window.AuthSessionManager && typeof window.AuthSessionManager.getToken === 'function') { const t=window.AuthSessionManager.getToken(); if(t)return String(t); } } catch (_) {}
    try { if (window.AuthStorage && typeof window.AuthStorage.getAuth === 'function') { const a=window.AuthStorage.getAuth(); const t=a?.token||a?.accessToken; if(t)return String(t); } } catch (_) {}
    for(const key of ['authToken','accessToken','token','USER_TOKEN','necpa_token','kynecta_token','kynecta_auth']){
      try { const raw=localStorage.getItem(key); if(!raw)continue; if(key==='kynecta_auth'){const a=JSON.parse(raw);if(a?.token)return String(a.token);} else if(!raw.startsWith('{')) return raw; } catch (_) {}
    }
    try { const raw=localStorage.getItem('kynecta_session'); if(raw){const s=JSON.parse(raw);if(s?.token)return String(s.token);} } catch (_) {}
    return '';
  };
  const userId=()=>{
    try { if(window.__GROUP_CALL_USER_ID)return String(window.__GROUP_CALL_USER_ID); } catch (_) {}
    try { if(window.currentUser?.id)return String(window.currentUser.id); if(window.currentUser?.userId)return String(window.currentUser.userId); } catch (_) {}
    try { if(window.AuthSessionManager && typeof window.AuthSessionManager.getSession==='function'){const s=window.AuthSessionManager.getSession();if(s?.userId)return String(s.userId);if(s?.user?.id)return String(s.user.id);} } catch (_) {}
    try { const raw=localStorage.getItem('kynecta_session');if(raw){const s=JSON.parse(raw);if(s?.userId)return String(s.userId);if(s?.user?.id)return String(s.user.id);} } catch (_) {}
    try { return String(localStorage.getItem('userId')||''); } catch (_) { return ''; }
  };
  async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};const t=token();if(t)headers.Authorization='Bearer '+t;const r=await fetch(apiBase()+path,{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Group call request failed (${r.status})`);return d;}
  function ensureUi(){if(state.root)return;const style=document.createElement('style');style.textContent=`#groupCallOverlay{position:fixed;inset:0;z-index:9999;background:#05070b;color:#fff;display:flex;flex-direction:column}#groupCallOverlay.gc-hidden{display:none!important}.gc-head{height:58px;display:flex;align-items:center;gap:12px;padding:8px 14px;background:#111827;border-bottom:1px solid #263244}.gc-title{font-weight:800;flex:1}.gc-status{font-size:11px;opacity:.75}.gc-grid{flex:1;display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px;padding:10px;overflow:auto}.gc-tile{position:relative;min-height:180px;background:#111827;border:1px solid #263244;border-radius:14px;overflow:hidden;display:grid;place-items:center}.gc-tile video{width:100%;height:100%;object-fit:cover;background:#020617}.gc-name{position:absolute;left:8px;bottom:8px;padding:4px 7px;border-radius:7px;background:#0009;font-size:11px}.gc-controls{display:flex;justify-content:center;gap:9px;padding:12px;background:#111827;border-top:1px solid #263244}.gc-btn{border:0;border-radius:12px;padding:11px 15px;background:#263244;color:#fff}.gc-btn.end{background:#dc2626}`;document.head.appendChild(style);const root=document.createElement('section');root.id='groupCallOverlay';root.className='gc-hidden';root.innerHTML=`<div class="gc-head"><div class="gc-title" id="gcTitle">Group call</div><div class="gc-status" id="gcStatus">Connecting…</div></div><div class="gc-grid" id="gcGrid"></div><div class="gc-controls"><button class="gc-btn" id="gcMute">🎙 Mute</button><button class="gc-btn" id="gcCamera">📷 Camera</button><button class="gc-btn end" id="gcEnd">End call</button></div>`;document.body.appendChild(root);state.root=root;state.grid=root.querySelector('#gcGrid');state.status=root.querySelector('#gcStatus');root.querySelector('#gcMute').onclick=toggleMute;root.querySelector('#gcCamera').onclick=toggleCamera;root.querySelector('#gcEnd').onclick=leave;}
  const setStatus=t=>{if(state.status)state.status.textContent=t};
  function tile(id,stream,name,muted=false){const key='gc-'+String(id).replace(/[^a-zA-Z0-9_-]/g,'_');let el=document.getElementById(key);if(!el){el=document.createElement('div');el.className='gc-tile';el.id=key;const video=document.createElement('video');video.autoplay=true;video.playsInline=true;video.muted=muted;el.appendChild(video);const label=document.createElement('div');label.className='gc-name';label.textContent=name||id;el.appendChild(label);state.grid.appendChild(el);}const video=el.querySelector('video');if(video.srcObject!==stream)video.srcObject=stream;return el;}
  async function getMedia(){if(state.localStream)return state.localStream;if(!navigator.mediaDevices?.getUserMedia)throw new Error('This browser does not support camera/microphone access.');try{state.localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:state.type==='video'});}catch(error){const name=error?.name||'MediaError';const messages={NotAllowedError:'Microphone/camera permission was denied. Allow access in your browser and try again.',NotFoundError:'No microphone or camera was found on this device.',NotReadableError:'The microphone or camera is already in use by another application.',SecurityError:'Camera/microphone access requires a secure HTTPS page.'};throw new Error(messages[name]||`Unable to access ${state.type==='video'?'camera and microphone':'microphone'} (${name}).`);}tile(state.currentUserId,state.localStream,'You',true);return state.localStream;}
  const rtcConfig=()=>({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]});
  async function ensurePeer(remoteId,initiator){const key=String(remoteId);let entry=state.peers.get(key);if(entry)return entry.pc;const pc=new RTCPeerConnection(rtcConfig());entry={pc,candidateQueue:[],makingOffer:false};state.peers.set(key,entry);const stream=await getMedia();stream.getTracks().forEach(track=>pc.addTrack(track,stream));pc.onicecandidate=e=>{if(e.candidate)sendSignal(remoteId,'ice-candidate',e.candidate.toJSON?e.candidate.toJSON():e.candidate).catch(console.warn)};pc.ontrack=e=>{const s=e.streams?.[0];if(s)tile(key,s,`Member ${remoteId}`)};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState))removePeer(key)};if(initiator){entry.makingOffer=true;try{const offer=await pc.createOffer();await pc.setLocalDescription(offer);await sendSignal(remoteId,'offer',pc.localDescription.toJSON?pc.localDescription.toJSON():pc.localDescription)}finally{entry.makingOffer=false}}return pc;}
  async function sendSignal(to,kind,data){if(!state.callId)return;await api(`/${encodeURIComponent(state.callId)}/signals`,{method:'POST',body:JSON.stringify({to:String(to),kind,data})});}
  async function handleSignal(signal){const from=String(signal.from);if(!from||from===state.currentUserId)return;if(signal.kind==='participant-left')return removePeer(from);if(signal.kind==='host-changed')return;if(signal.kind==='participant-joined'){if(state.currentUserId<from)await ensurePeer(from,true);return}const pc=await ensurePeer(from,false);const entry=state.peers.get(from);if(!entry)return;if(signal.kind==='offer'){await pc.setRemoteDescription(new RTCSessionDescription(signal.data));while(entry.candidateQueue.length)await pc.addIceCandidate(entry.candidateQueue.shift());const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await sendSignal(from,'answer',pc.localDescription.toJSON?pc.localDescription.toJSON():pc.localDescription)}else if(signal.kind==='answer'){await pc.setRemoteDescription(new RTCSessionDescription(signal.data));while(entry.candidateQueue.length)await pc.addIceCandidate(entry.candidateQueue.shift())}else if(signal.kind==='ice-candidate'){const candidate=new RTCIceCandidate(signal.data);if(pc.remoteDescription)await pc.addIceCandidate(candidate);else entry.candidateQueue.push(candidate)}}
  function removePeer(id){const key=String(id);const entry=state.peers.get(key);if(entry){try{entry.pc.close()}catch(_){}}state.peers.delete(key);document.getElementById('gc-'+key.replace(/[^a-zA-Z0-9_-]/g,'_'))?.remove();}
  async function poll(){if(!state.active)return;try{const r=await api(`/${encodeURIComponent(state.callId)}/signals?after=${state.cursor}`);state.cursor=Number(r.cursor||state.cursor);for(const signal of r.signals||[])await handleSignal(signal);const room=await api(`/${encodeURIComponent(state.callId)}`);if(!room?.room?.active)return leave(false);const participants=room.room.participants||[];setStatus(`${participants.length} participant${participants.length===1?'':'s'}`);for(const p of participants){const id=String(p.userId);if(id!==state.currentUserId&&!state.peers.has(id)&&state.currentUserId<id)await ensurePeer(id,true)}}catch(e){if(state.active)console.warn('[GroupCall] polling:',e.message)}if(state.active)state.pollTimer=setTimeout(poll,900)}
  const gs={chatId:null,lastId:0,timer:null,running:false,originalFetch:null};
  const groupVisible=()=>{const el=document.getElementById('chat');return !!el&&!el.classList.contains('hidden')};
  const headers=()=>token()?{Authorization:'Bearer '+token()}:{};
  function messagesOf(d){const x=d?.data?.messages||d?.data||d?.messages||d;if(Array.isArray(x))return x;if(x&&x.id)return[x];return[];}
  function remember(ms){for(const m of ms){const id=Number(m?.id);if(Number.isFinite(id)&&id>gs.lastId)gs.lastId=id;}}
  function appendGroupMessage(m){if(!m?.id||!groupVisible()||String(m.chatId)!==String(gs.chatId))return;const box=document.getElementById('messages');if(!box)return;if(Array.from(box.querySelectorAll('.row')).some(x=>x.dataset.messageId===String(m.id)))return;const me=String(m.senderId||m.userId)===String(window.__GROUP_CALL_USER_ID||userId());const row=document.createElement('div');row.className='row'+(me?' mine':'');row.dataset.messageId=String(m.id);const b=document.createElement('div');b.className='bubble';if(!me){const s=document.createElement('div');s.className='sender';s.textContent=m.senderUsername||m.sender?.displayName||m.sender?.username||'Member';b.appendChild(s)}let marker=null;try{marker=JSON.parse(m.content||'')}catch(_){}if(marker?.__groupCall&&marker.callId){const body=document.createElement('div');body.textContent='📞 Group call started';const join=document.createElement('button');join.className='smallbtn';join.style.marginTop='7px';join.textContent='Join call';join.onclick=()=>window.GroupCall?.join(marker.callId,marker.type);b.append(body,join)}else{const body=document.createElement('div');body.textContent=m.content||'';b.appendChild(body)}const t=document.createElement('div');t.className='time';t.textContent=new Date(m.createdAt||m.sentAt||Date.now()).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});b.appendChild(t);row.appendChild(b);box.appendChild(row);box.scrollTop=box.scrollHeight;}
  async function syncGroupMessages(){if(!gs.running||!gs.chatId||!groupVisible())return;try{const q=gs.lastId?`?sinceId=${encodeURIComponent(gs.lastId)}&limit=100`:'?limit=100';const apiRoot=typeof window.__getApiBase==='function'?window.__getApiBase():'';const r=await fetch(`${apiRoot}/messages/${encodeURIComponent(gs.chatId)}/sync${q}`,{headers:headers()});if(!r.ok)return;const d=await r.json().catch(()=>({}));const ms=messagesOf(d).sort((a,b)=>Number(a.id||0)-Number(b.id||0));ms.forEach(appendGroupMessage);remember(ms);}catch(e){console.warn('[Groups] message sync:',e.message)}}
  function startSync(id){if(!id)return;gs.chatId=String(id);gs.running=true;gs.lastId=0;if(gs.timer)clearInterval(gs.timer);gs.timer=setInterval(syncGroupMessages,1000);syncGroupMessages();}
  function stopSync(){gs.running=false;gs.chatId=null;gs.lastId=0;if(gs.timer)clearInterval(gs.timer);gs.timer=null;}
  function installFetchObserver(){if(gs.originalFetch||typeof window.fetch!=='function')return;gs.originalFetch=window.fetch.bind(window);window.fetch=async function(input,init){const url=typeof input==='string'?input:input?.url||'';const result=await gs.originalFetch(input,init);try{const u=String(url);const match=u.match(/\/messages\/(\d+)(?:\?|$)/);if(match&&!u.includes('/sync')&&result.ok){const d=await result.clone().json().catch(()=>null);const ms=messagesOf(d);if(ms.length){startSync(match[1]);remember(ms)}}else if((u.endsWith('/messages')||u.includes('/messages?'))&&result.ok){const d=await result.clone().json().catch(()=>null);const ms=messagesOf(d);if(ms[0]?.chatId){startSync(ms[0].chatId);remember(ms)}}}catch(_){}return result};const obs=new MutationObserver(()=>{if(!groupVisible()&&gs.running)stopSync()});obs.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});}
  installFetchObserver();

  async function start(type,group){if(!group?.id)throw new Error('No group selected.');ensureUi();if(state.active)return;state.currentUserId=userId();if(!state.currentUserId)throw new Error('Your session/user ID is not available.');state.chatId=String(group.id);state.type=type==='video'?'video':'audio';state.root.classList.remove('gc-hidden');state.grid.innerHTML='';setStatus('Starting…');try{await getMedia();const created=await api('/',{method:'POST',body:JSON.stringify({chatId:state.chatId,callType:state.type})});state.room=created.room;state.callId=state.room.callId;state.active=true;state.cursor=0;state.root.querySelector('#gcTitle').textContent=`${group.name||'Group'} · ${state.type}`;setStatus('Waiting for members…');try{const marker=JSON.stringify({__groupCall:true,callId:state.callId,type:state.type});await fetch((typeof window.__getApiBase==='function'?window.__getApiBase():'')+'/messages',{method:'POST',headers:{'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}: {})},body:JSON.stringify({chatId:state.chatId,content:marker,type:'text',clientMessageId:'gcall_'+state.callId})}).catch(()=>{})}catch(_){}await poll()}catch(e){stopLocal();state.active=false;state.callId=null;state.chatId=null;state.room=null;state.root.classList.add('gc-hidden');setStatus(e.message||'Unable to start group call');throw e}}
  async function join(callId,type='audio'){ensureUi();if(state.active)return;state.currentUserId=userId();if(!state.currentUserId)throw new Error('Your session/user ID is not available.');state.callId=callId;state.type=type==='video'?'video':'audio';state.root.classList.remove('gc-hidden');try{await getMedia();const r=await api(`/${encodeURIComponent(callId)}/join`,{method:'POST',body:JSON.stringify({media:state.type})});state.room=r.room;state.chatId=String(state.room.chatId);state.active=true;state.cursor=0;for(const p of state.room.participants||[]){const id=String(p.userId);if(id!==state.currentUserId&&state.currentUserId<id)await ensurePeer(id,true)}await poll()}catch(e){stopLocal();state.active=false;state.callId=null;state.chatId=null;state.room=null;state.root.classList.add('gc-hidden');setStatus(e.message||'Unable to join group call');throw e}}
  function stopLocal(){if(state.localStream)state.localStream.getTracks().forEach(t=>t.stop());state.localStream=null;state.peers.forEach(({pc})=>{try{pc.close()}catch(_){}});state.peers.clear();}
  async function leave(notify=true){if(!state.active&&!state.callId)return;const id=state.callId;state.active=false;if(state.pollTimer)clearTimeout(state.pollTimer);state.pollTimer=null;if(notify&&id)await api(`/${encodeURIComponent(id)}/leave`,{method:'POST'}).catch(()=>{});stopLocal();state.callId=null;state.room=null;state.chatId=null;if(state.root)state.root.classList.add('gc-hidden');}
  function toggleMute(){const track=state.localStream?.getAudioTracks?.()[0];if(!track)return;track.enabled=!track.enabled;const btn=state.root?.querySelector('#gcMute');if(btn)btn.textContent=track.enabled?'🎙 Mute':'🔇 Unmute'}
  function toggleCamera(){const track=state.localStream?.getVideoTracks?.()[0];if(!track)return;track.enabled=!track.enabled;const btn=state.root?.querySelector('#gcCamera');if(btn)btn.textContent=track.enabled?'📷 Camera':'🚫 Camera'}
  window.GroupCall={start,join,leave,isActive:()=>state.active};
})();

(() => { const load=()=>{if(document.querySelector('script[data-group-advanced]'))return;const s=document.createElement('script');s.src='/js/group-advanced.js';s.dataset.groupAdvanced='1';s.defer=true;document.head.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();
