/* Kynecta group-only Sender Keys v2. Independent from direct-message encryption. */
(function(global){
'use strict';
const PIPELINE='KYN-GROUP-V2',ALGORITHM='SenderKey-AES256GCM-v2';
const states=new Map(),stateFetch=new Map(),te=new TextEncoder(),td=new TextDecoder(),subtle=crypto.subtle;
const base=()=>String(global.__getApiBase?.()||global.API_BASE_URL||'').replace(/\/$/,'');
const token=()=>global.__kynToken||global.__accessToken||global.AuthSessionManager?.getToken?.()||global.authToken||localStorage.getItem('authToken')||localStorage.getItem('accessToken')||localStorage.getItem('token')||'';
const me=()=>Number(global._kynCurrentUserId||localStorage.getItem('userId')||localStorage.getItem('currentUserId')||0);
const b64=u=>btoa(String.fromCharCode(...new Uint8Array(u))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function req(path,opt={}){const h={...(opt.headers||{})},t=token();if(t)h.Authorization='Bearer '+t;if(opt.body)h['Content-Type']='application/json';let r=await fetch(base()+path,{...opt,headers:h});if(r.status===401&&global.NecpaSessionResilience){try{if(await global.NecpaSessionResilience.refreshAccessToken(base())){const nt=token();if(nt)h.Authorization='Bearer '+nt;r=await fetch(base()+path,{...opt,headers:h})}}catch(_){}}
const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||'Group request failed');Object.assign(e,d);throw e}return d}
const idkey=(g,e,o)=>`kyn_gsk_v2_${g}_${e}_${o}`;
async function waitReady(){if(global.KynectaE2E?.enabled)return true;if(global.KynectaE2E?.waitForEnabledBounded)return global.KynectaE2E.waitForEnabledBounded(15000);return false}
function identity(){const p=global.KynectaE2E?.getMyIdentityPrivateKey?.();if(!p)throw new Error('Group identity key is not ready');return p}
async function publicKey(userId){const r=await req('/encryption/keys/'+encodeURIComponent(userId)),p=r?.data?.publicKey;if(!p)throw new Error('Member '+userId+' has no registered identity key');return subtle.importKey('spki',unb64(p),{name:'ECDH',namedCurve:'P-256'},true,['deriveBits'])}
async function wrapKey(rawB64,recipientId){const bits=await subtle.deriveBits({name:'ECDH',public:await publicKey(recipientId)},identity(),256),mat=await subtle.importKey('raw',bits,{name:'HKDF'},false,['deriveKey']),key=await subtle.deriveKey({name:'HKDF',salt:new Uint8Array(32),info:te.encode('KYN-GROUP-V2/SENDER-KEY-WRAP'),hash:'SHA-256'},mat,{name:'AES-GCM',length:256},false,['encrypt','decrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),ct=await subtle.encrypt({name:'AES-GCM',iv},key,te.encode(rawB64));return JSON.stringify({v:2,iv:b64(iv),ct:b64(ct)})}
async function unwrapKey(envelope,ownerId){const e=typeof envelope==='string'?JSON.parse(envelope):envelope;if(e?.v!==2)throw new Error('Unsupported group key envelope');const bits=await subtle.deriveBits({name:'ECDH',public:await publicKey(ownerId)},identity(),256),mat=await subtle.importKey('raw',bits,{name:'HKDF'},false,['deriveKey']),key=await subtle.deriveKey({name:'HKDF',salt:new Uint8Array(32),info:te.encode('KYN-GROUP-V2/SENDER-KEY-WRAP'),hash:'SHA-256'},mat,{name:'AES-GCM',length:256},false,['encrypt','decrypt']),pt=await subtle.decrypt({name:'AES-GCM',iv:unb64(e.iv)},key,unb64(e.ct));return td.decode(pt)}
async function hmac(raw,label){const k=await subtle.importKey('raw',raw,{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await subtle.sign('HMAC',k,te.encode(label)))}
const aesKey=raw=>subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);
async function saveState(st){try{const p=JSON.stringify({chain:b64(st.chain),privateJwk:st.privateJwk||null,publicJwk:st.publicJwk||null,iteration:st.iteration}),w=await global.KynectaE2E.wrapForLocalStorage(b64(te.encode(p)));if(w)localStorage.setItem(idkey(st.groupId,st.epoch,st.ownerId),w)}catch(_){}}
async function loadState(g,e,o){try{const w=localStorage.getItem(idkey(g,e,o));if(!w)return null;const raw=await global.KynectaE2E.unwrapFromLocalStorage(w),x=JSON.parse(td.decode(unb64(raw))),priv=x.privateJwk?await subtle.importKey('jwk',x.privateJwk,{name:'ECDSA',namedCurve:'P-256'},true,['sign']):null;return{groupId:Number(g),epoch:Number(e),ownerId:Number(o),chain:unb64(x.chain),privateKey:priv,privateJwk:x.privateJwk||null,publicJwk:x.publicJwk||null,iteration:Number(x.iteration)||0,skipped:new Map()}}catch(_){return null}}
async function createSenderState(g,e){const kp=await subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),priv=await subtle.exportKey('jwk',kp.privateKey),pub=await subtle.exportKey('jwk',kp.publicKey);return{groupId:Number(g),epoch:Number(e),ownerId:me(),chain:crypto.getRandomValues(new Uint8Array(32)),privateKey:kp.privateKey,privateJwk:priv,publicJwk:pub,iteration:0,skipped:new Map()}}
async function state(g,force=false){const k=String(g);if(!force&&stateFetch.has(k))return stateFetch.get(k);const p=req('/group-messages/'+encodeURIComponent(g)+'/crypto/state').then(x=>x.data||{});stateFetch.set(k,p);try{return await p}finally{if(stateFetch.get(k)===p)stateFetch.delete(k)}}
function keyEntry(s,e,o){const cur=(s?.senderKeys||[]).find(x=>Number(x.epoch)===Number(e)&&Number(x.ownerId)===Number(o));if(cur)return cur;for(const h of(s?.history||[])){const x=(h.senderKeys||[]).find(y=>Number(y.epoch)===Number(e)&&Number(y.ownerId)===Number(o));if(x)return x}return null}
async function distribute(g,e,st,members){const raw=b64(te.encode(JSON.stringify({chain:b64(st.chain),publicJwk:st.publicJwk}))),ds=[];for(const id of [...new Set(members.map(Number).filter(Boolean))])ds.push({userId:id,deviceId:'primary',ciphertext:await wrapKey(raw,id),algorithm:ALGORITHM});await req('/group-messages/'+encodeURIComponent(g)+'/crypto/rotate',{method:'POST',body:JSON.stringify({epoch:e,distributions:ds})});states.set(idkey(g,e,st.ownerId),st);await saveState(st);return st}
async function ensureSenderKey(g,members){if(!(await waitReady()))throw new Error('Secure group identity is not ready');const gid=Number(g),owner=me();for(let attempt=0;attempt<4;attempt++){const s=await state(gid,true),epoch=Math.max(1,Number(s.epoch)||1),entry=keyEntry(s,epoch,owner);let st=states.get(idkey(gid,epoch,owner))||await loadState(gid,epoch,owner);if(entry?.distribution&&!st)st=await getReceiverState(gid,epoch,owner);if(st&&entry?.distribution){states.set(idkey(gid,epoch,owner),st);return st}if(st&&!entry?.distribution){try{return await distribute(gid,epoch,st,members)}catch(e){if(e.code==='GROUP_SENDER_KEY_INCOMPLETE'){await sleep(500);continue}throw e}}st=await createSenderState(gid,epoch);try{return await distribute(gid,epoch,st,members)}catch(e){if(e.status===409){await sleep(300);continue}throw e}}throw new Error('Group sender key is still synchronizing; retry in a moment')}
async function getReceiverState(g,e,o){const k=idkey(g,e,o);let st=states.get(k)||await loadState(g,e,o);if(st){states.set(k,st);return st}const s=await state(g,true),entry=keyEntry(s,e,o);if(!entry?.distribution)throw new Error('Sender key for this group message is not available');const raw=await unwrapKey(entry.distribution.ciphertext,o),b=JSON.parse(td.decode(unb64(raw))),priv=await subtle.importKey('jwk',b.privateJwk,{name:'ECDSA',namedCurve:'P-256'},true,['sign']);st={groupId:Number(g),epoch:Number(e),ownerId:Number(o),chain:unb64(b.chain),privateKey:null,privateJwk:null,publicJwk:b.publicJwk||null,iteration:0,skipped:new Map()};states.set(k,st);await saveState(st);return st}
const signInput=(g,e,o,i,iv,ct)=>te.encode([PIPELINE,g,e,o,i,iv,ct].join('|'));
async function encryptForGroup(g,plaintext,members){const st=await ensureSenderKey(g,members),i=st.iteration,mk=await hmac(st.chain,'message:'+i),next=await hmac(st.chain,'chain:'+i),key=await aesKey(mk),iv=crypto.getRandomValues(new Uint8Array(12)),ct=await subtle.encrypt({name:'AES-GCM',iv},key,te.encode(String(plaintext))),ivb=b64(iv),ctb=b64(ct),sig=await subtle.sign({name:'ECDSA',hash:{name:'SHA-256'}},st.privateKey,signInput(g,st.epoch,st.ownerId,i,ivb,ctb));st.chain=next;st.iteration++;await saveState(st);return JSON.stringify({v:2,pipeline:PIPELINE,algorithm:ALGORITHM,group:String(g),epoch:st.epoch,owner:st.ownerId,iteration:i,iv:ivb,ct:ctb,sig:b64(sig),publicKey:st.publicJwk})}
async function decryptForGroup(g,ciphertext){let e;try{e=JSON.parse(ciphertext)}catch(_){return ciphertext}if(!e||e.v!==2||e.pipeline!==PIPELINE)return ciphertext;const st=await getReceiverState(g,Number(e.epoch),Number(e.owner)),pub=await subtle.importKey('jwk',e.publicKey,{name:'ECDSA',namedCurve:'P-256'},false,['verify']),ok=await subtle.verify({name:'ECDSA',hash:{name:'SHA-256'}},pub,unb64(e.sig),signInput(g,e.epoch,e.owner,e.iteration,e.iv,e.ct));if(!ok)throw new Error('Group message signature verification failed');let mk;if(Number(e.iteration)<st.iteration){mk=st.skipped.get(Number(e.iteration));if(!mk)throw new Error('Group message is too old for this sender-key state')}else{while(st.iteration<Number(e.iteration)){const x=await hmac(st.chain,'message:'+st.iteration);st.chain=await hmac(st.chain,'chain:'+st.iteration);st.skipped.set(st.iteration,x);if(st.skipped.size>200)st.skipped.delete(st.skipped.keys().next().value);st.iteration++}mk=await hmac(st.chain,'message:'+st.iteration);st.chain=await hmac(st.chain,'chain:'+st.iteration);st.iteration++}const pt=await subtle.decrypt({name:'AES-GCM',iv:unb64(e.iv)},await aesKey(mk),unb64(e.ct));await saveState(st);return td.decode(pt)}
global.KynectaGroupE2E={ensureSenderKey,encryptForGroup,decryptForGroup,initGroup:async g=>{await waitReady();try{await state(g,true)}catch(_){}}};
console.log('[KynectaGroupE2E] Group-only Sender Keys v2 loaded');
})(window);