// GENERATED FILE - do not edit by hand. Source: QUESTION_BANK in game-v3.html + curated additions, WC_LEVELS in games-crossword-v4.js.
package com.necpa;

/** Static content for the native arcade (trivia questions and word-connect levels). */
public final class NecpraGameData {
    private NecpraGameData() {}

    /** subject \t tier \t correctIndex \t question \t a0 \t a1 \t a2 \t a3 */
    public static final String[] TRIVIA = {
        "geography\t1\t0\tWhat is the capital of France?\tParis\tRome\tMadrid\tBerlin",
        "geography\t1\t2\tHow many continents are there on Earth?\t5\t6\t7\t8",
        "science\t1\t1\tWhat is the boiling point of water in Celsius?\t90\t100\t110\t120",
        "science\t1\t1\tWhich planet is known as the Red Planet?\tEarth\tMars\tVenus\tJupiter",
        "math\t1\t2\tHow many days are there in a leap year?\t364\t365\t366\t367",
        "geography\t1\t3\tWhat is the largest ocean on Earth?\tAtlantic\tIndian\tArctic\tPacific",
        "math\t1\t1\tHow many sides does a hexagon have?\t5\t6\t7\t8",
        "science\t1\t2\tWhich gas do plants absorb from the air?\tOxygen\tNitrogen\tCarbon dioxide\tHelium",
        "math\t1\t1\tWhat is 12 \u00d7 8?\t86\t96\t108\t112",
        "geography\t1\t1\tWhich country is home to Mount Fuji?\tChina\tJapan\tNepal\tThailand",
        "science\t1\t1\tWhat is the freezing point of water in Celsius?\t-10\t0\t10\t32",
        "science\t1\t1\tHow many legs does a spider have?\t6\t8\t10\t12",
        "science\t1\t2\tWhat is the largest planet in our solar system?\tSaturn\tNeptune\tJupiter\tUranus",
        "geography\t1\t2\tWhich ocean is the smallest?\tAtlantic\tIndian\tArctic\tPacific",
        "science\t1\t2\tHow many colors are in a rainbow?\t5\t6\t7\t8",
        "geography\t1\t2\tWhat is the currency of Japan?\tWon\tYuan\tYen\tRinggit",
        "general\t2\t1\tWho wrote the play \"Romeo and Juliet\"?\tCharles Dickens\tWilliam Shakespeare\tMark Twain\tJane Austen",
        "science\t2\t2\tWhat is the chemical symbol for gold?\tAg\tGd\tAu\tGo",
        "geography\t2\t1\tWhat is the tallest mountain in the world?\tK2\tMount Everest\tKilimanjaro\tDenali",
        "science\t2\t1\tHow many bones are in the adult human body?\t186\t206\t226\t246",
        "math\t2\t2\tWhat is the smallest prime number?\t0\t1\t2\t3",
        "science\t2\t2\tWhich planet is closest to the Sun?\tVenus\tEarth\tMercury\tMars",
        "math\t2\t2\tWhat is the square root of 144?\t10\t11\t12\t13",
        "geography\t2\t1\tIn which continent is the Sahara Desert located?\tAsia\tAfrica\tAustralia\tSouth America",
        "general\t2\t1\tWhat is the main ingredient in guacamole?\tTomato\tAvocado\tLime\tOnion",
        "general\t2\t2\tHow many strings does a standard guitar have?\t4\t5\t6\t7",
        "science\t2\t1\tWhich element has the chemical symbol \"O\"?\tOsmium\tOxygen\tGold\tIron",
        "science\t2\t2\tWhat is the hardest natural substance on Earth?\tQuartz\tSteel\tDiamond\tGranite",
        "math\t2\t2\tHow many minutes are in a full day?\t1220\t1320\t1440\t1500",
        "math\t2\t1\tWhich shape has three sides?\tSquare\tTriangle\tPentagon\tHexagon",
        "science\t2\t2\tWhat is the powerhouse of the cell called?\tNucleus\tRibosome\tMitochondria\tCytoplasm",
        "general\t2\t1\tWhich language runs natively in a web browser?\tPython\tJavaScript\tC++\tSQL",
        "science\t3\t1\tWhat is the speed of light in a vacuum (approx.)?\t150,000 km/s\t300,000 km/s\t450,000 km/s\t600,000 km/s",
        "science\t3\t2\tWho developed the theory of general relativity?\tIsaac Newton\tNiels Bohr\tAlbert Einstein\tGalileo Galilei",
        "geography\t3\t2\tWhat is the capital of Australia?\tSydney\tMelbourne\tCanberra\tPerth",
        "science\t3\t2\tWhich vitamin is produced when skin is exposed to sunlight?\tVitamin A\tVitamin C\tVitamin D\tVitamin K",
        "science\t3\t1\tWhat is the atomic number of hydrogen?\t0\t1\t2\t3",
        "science\t3\t2\tWhich gas makes up most of Earth's atmosphere?\tOxygen\tCarbon dioxide\tNitrogen\tArgon",
        "history\t3\t1\tWho painted the Mona Lisa?\tMichelangelo\tLeonardo da Vinci\tRaphael\tDonatello",
        "science\t3\t1\tWhat is the smallest bone in the human body?\tFemur\tStapes\tRadius\tTibia",
        "science\t3\t2\tWhat is the study of earthquakes called?\tVolcanology\tMeteorology\tSeismology\tGeology",
        "science\t3\t2\tIn chemistry, what does \"pH\" measure?\tTemperature\tDensity\tAcidity/alkalinity\tPressure",
        "science\t3\t2\tWhat is the largest species of shark?\tGreat white shark\tHammerhead shark\tWhale shark\tTiger shark",
        "history\t3\t1\tWhich country invented paper?\tEgypt\tChina\tGreece\tIndia",
        "general\t3\t2\tWhat is a word called that reads the same forwards and backwards?\tAnagram\tAcronym\tPalindrome\tSynonym",
        "science\t3\t2\tWhich organ in the human body produces insulin?\tLiver\tKidney\tPancreas\tSpleen",
        "geography\t3\t2\tWhat is the capital of Canada?\tToronto\tVancouver\tOttawa\tMontreal",
        "science\t3\t0\tWhat is the chemical formula for table salt?\tNaCl\tH2O\tCO2\tKCl",
        "science\t1\t0\tWhat force keeps the planets in orbit around the Sun?\tGravity\tMagnetism\tFriction\tStatic electricity",
        "science\t2\t0\tWhat is the chemical symbol for sodium?\tNa\tSo\tS\tSd",
        "science\t2\t0\tWhich gas is the most abundant in the Sun?\tHydrogen\tOxygen\tHelium\tCarbon dioxide",
        "science\t1\t0\tWhich organ pumps blood around the human body?\tHeart\tLungs\tLiver\tKidney",
        "science\t1\t0\tWhat do bees collect from flowers to make honey?\tNectar\tPollen only\tSap\tWater",
        "science\t1\t0\tWhat is the process plants use to make food from sunlight called?\tPhotosynthesis\tRespiration\tDigestion\tFermentation",
        "science\t2\t0\tWhich blood cells carry oxygen around the body?\tRed blood cells\tWhite blood cells\tPlatelets\tPlasma cells",
        "science\t2\t0\tWhat is the chemical symbol for iron?\tFe\tIr\tIn\tFi",
        "science\t1\t0\tA dolphin is what type of animal?\tMammal\tFish\tReptile\tAmphibian",
        "science\t1\t0\tHow many planets are there in our solar system?\t8\t7\t9\t10",
        "science\t2\t0\tWhat is the SI unit of electric current?\tAmpere\tVolt\tOhm\tWatt",
        "science\t2\t0\tWhich part of a cell contains its genetic material?\tNucleus\tCell wall\tVacuole\tMembrane",
        "science\t1\t0\tWhat is the closest star to Earth?\tThe Sun\tProxima Centauri\tSirius\tThe North Star",
        "science\t2\t0\tSound cannot travel through which of these?\tA vacuum\tWater\tSteel\tAir",
        "science\t1\t0\tWhich planet is best known for its bright rings?\tSaturn\tMars\tMercury\tVenus",
        "science\t2\t0\tWhich scientist formulated the laws of motion and universal gravitation?\tIsaac Newton\tAlbert Einstein\tNikola Tesla\tCharles Darwin",
        "science\t3\t0\tWhat is the hardest substance in the human body?\tTooth enamel\tBone\tCartilage\tFingernail",
        "science\t1\t0\tAnimals that eat only plants are called what?\tHerbivores\tCarnivores\tOmnivores\tInsectivores",
        "science\t3\t0\tWhat is the SI unit of force?\tNewton\tJoule\tPascal\tWatt",
        "science\t2\t0\tWhat is the Earth's outermost solid layer called?\tCrust\tMantle\tOuter core\tInner core",
        "math\t1\t0\tWhat is 15 + 27?\t42\t32\t52\t41",
        "math\t1\t0\tWhat is 9 \u00d7 7?\t63\t56\t72\t54",
        "math\t1\t0\tHow many degrees are there in a right angle?\t90\t45\t180\t60",
        "math\t1\t0\tWhat is half of 250?\t125\t150\t105\t115",
        "math\t1\t0\tWhat is 100 \u00f7 4?\t25\t20\t40\t50",
        "math\t2\t0\tThe angles inside a triangle add up to how many degrees?\t180\t90\t270\t360",
        "math\t2\t0\tWhat is 15% of 200?\t30\t15\t20\t45",
        "math\t1\t0\tWhat is 5 squared?\t25\t10\t15\t55",
        "math\t2\t0\tWhat is the next prime number after 7?\t11\t9\t10\t13",
        "math\t2\t0\tWhat is 3/4 written as a decimal?\t0.75\t0.34\t0.43\t0.65",
        "math\t2\t0\tA square has sides of length 6. What is its perimeter?\t24\t12\t36\t18",
        "math\t1\t0\tWhat is the area of a rectangle that is 8 by 5?\t40\t13\t26\t45",
        "math\t1\t0\tWhat is the square root of 81?\t9\t8\t7\t11",
        "math\t2\t0\tWhat is 2 to the power of 6?\t64\t12\t32\t128",
        "math\t1\t0\tHow many sides does an octagon have?\t8\t6\t7\t10",
        "math\t2\t0\tWhat is the sum of 1 + 2 + 3 + 4 + 5?\t15\t10\t20\t12",
        "math\t2\t0\tIf 3x = 21, what is x?\t7\t6\t8\t18",
        "math\t1\t0\tWhat is pi, rounded to two decimal places?\t3.14\t3.41\t3.12\t3.24",
        "math\t3\t0\tWhat is the cube root of 27?\t3\t9\t6\t2",
        "math\t3\t0\tWhat is the lowest common multiple of 4 and 6?\t12\t24\t10\t2",
        "geography\t2\t0\tWhat is the longest river in Africa?\tThe Nile\tThe Congo\tThe Niger\tThe Zambezi",
        "geography\t3\t0\tWhich is the largest country in Africa by area?\tAlgeria\tNigeria\tEgypt\tSouth Africa",
        "geography\t1\t0\tWhat is the capital of Japan?\tTokyo\tOsaka\tKyoto\tSeoul",
        "geography\t1\t0\tWhat is the capital of Egypt?\tCairo\tAlexandria\tGiza\tLuxor",
        "geography\t2\t0\tWhat is the capital of Brazil?\tBras\u00edlia\tRio de Janeiro\tS\u00e3o Paulo\tSalvador",
        "geography\t1\t0\tOn which continent is Brazil?\tSouth America\tAfrica\tEurope\tAsia",
        "geography\t2\t0\tIn which country is Mount Kilimanjaro?\tTanzania\tKenya\tUganda\tEthiopia",
        "geography\t2\t0\tWhich is the smallest continent by land area?\tAustralia / Oceania\tEurope\tAntarctica\tSouth America",
        "geography\t2\t0\tWhat is the capital of Nigeria?\tAbuja\tLagos\tKano\tAccra",
        "geography\t1\t0\tWhich ocean lies between Africa and Australia?\tIndian Ocean\tAtlantic Ocean\tArctic Ocean\tPacific Ocean",
        "geography\t1\t0\tMost of the Amazon rainforest lies in which country?\tBrazil\tPeru\tColombia\tArgentina",
        "geography\t1\t0\tWhich river flows through London?\tThe Thames\tThe Seine\tThe Danube\tThe Tiber",
        "geography\t1\t0\tWhat is the capital of Italy?\tRome\tMilan\tVenice\tNaples",
        "geography\t2\t0\tWhat is the capital of Ethiopia?\tAddis Ababa\tNairobi\tKampala\tKhartoum",
        "geography\t1\t0\tWhat is the capital of Germany?\tBerlin\tMunich\tHamburg\tVienna",
        "geography\t3\t0\tWhich strait separates Spain from Morocco?\tStrait of Gibraltar\tBosphorus\tStrait of Hormuz\tBering Strait",
        "geography\t2\t0\tWhat is the longest river in South America?\tThe Amazon\tThe Orinoco\tThe Paran\u00e1\tThe Magdalena",
        "geography\t3\t0\tIn which country is the city of Marrakech?\tMorocco\tTunisia\tEgypt\tAlgeria",
        "geography\t1\t0\tWhich country is known as the Land of the Rising Sun?\tJapan\tChina\tThailand\tKorea",
        "geography\t2\t0\tWhich desert covers much of Botswana?\tThe Kalahari\tThe Sahara\tThe Namib\tThe Gobi",
        "history\t1\t0\tWho was the first President of the United States?\tGeorge Washington\tAbraham Lincoln\tThomas Jefferson\tJohn Adams",
        "history\t1\t0\tIn which year did World War II end?\t1945\t1939\t1918\t1950",
        "history\t1\t0\tWhich ancient civilisation built the pyramids of Giza?\tAncient Egyptians\tRomans\tGreeks\tPersians",
        "history\t1\t0\tWho was the first person to walk on the Moon?\tNeil Armstrong\tBuzz Aldrin\tYuri Gagarin\tJohn Glenn",
        "history\t2\t0\tWhich empire was Julius Caesar a leader of?\tRoman\tGreek\tOttoman\tMongol",
        "history\t2\t0\tIn which year did the Titanic sink?\t1912\t1905\t1920\t1898",
        "history\t2\t0\tWho painted the ceiling of the Sistine Chapel?\tMichelangelo\tLeonardo da Vinci\tRaphael\tBotticelli",
        "history\t2\t0\tWhich famous wall fell in 1989?\tThe Berlin Wall\tThe Great Wall\tHadrian's Wall\tThe Western Wall",
        "history\t3\t0\tWho was the first woman to win a Nobel Prize?\tMarie Curie\tMother Teresa\tFlorence Nightingale\tRosalind Franklin",
        "history\t3\t0\tThe French Revolution began in which year?\t1789\t1769\t1815\t1848",
        "history\t2\t0\tWho discovered penicillin?\tAlexander Fleming\tLouis Pasteur\tMarie Curie\tEdward Jenner",
        "history\t1\t0\tWhich explorer reached the Americas in 1492?\tChristopher Columbus\tVasco da Gama\tFerdinand Magellan\tMarco Polo",
        "history\t1\t0\tWhich Chinese structure was built to protect against invasions?\tThe Great Wall\tThe Forbidden City\tThe Terracotta Army\tThe Summer Palace",
        "history\t1\t0\tWho became South Africa's president in 1994 after the end of apartheid?\tNelson Mandela\tDesmond Tutu\tThabo Mbeki\tSteve Biko",
        "history\t3\t0\tWho was the principal author of the US Declaration of Independence?\tThomas Jefferson\tBenjamin Franklin\tGeorge Washington\tAlexander Hamilton",
        "history\t2\t0\tWhich ship carried the Pilgrims to America in 1620?\tThe Mayflower\tThe Santa Maria\tThe Endeavour\tThe Beagle",
        "history\t2\t0\tIn which year did humans first land on the Moon?\t1969\t1959\t1975\t1981",
        "history\t2\t0\tWhich civilisation built Machu Picchu?\tThe Inca\tThe Aztec\tThe Maya\tThe Olmec",
        "history\t2\t0\tWho was Britain's Prime Minister for most of World War II?\tWinston Churchill\tNeville Chamberlain\tClement Attlee\tMargaret Thatcher",
        "history\t2\t0\tWhich ancient city was buried by the eruption of Mount Vesuvius in 79 AD?\tPompeii\tAthens\tCarthage\tTroy",
        "general\t1\t0\tHow many players from one team are on the pitch in a football (soccer) match?\t11\t9\t10\t12",
        "general\t1\t0\tWhich sport is played with a shuttlecock?\tBadminton\tTennis\tSquash\tTable tennis",
        "general\t2\t0\tHow many rings are there on the Olympic flag?\t5\t4\t6\t7",
        "general\t1\t0\tIn which sport would you score with a slam dunk?\tBasketball\tVolleyball\tNetball\tHandball",
        "general\t1\t0\tWhat is the largest mammal in the world?\tBlue whale\tAfrican elephant\tGiraffe\tHippopotamus",
        "general\t1\t0\tWhich animal is the fastest on land?\tCheetah\tLion\tLeopard\tHorse",
        "general\t3\t0\tHow many keys does a standard piano have?\t88\t76\t64\t100",
        "general\t2\t0\tWhat is the main language spoken in Brazil?\tPortuguese\tSpanish\tEnglish\tFrench",
        "general\t3\t0\tWhich fruit has its seeds on the outside?\tStrawberry\tRaspberry\tGrape\tCherry",
        "general\t1\t0\tWhat colour do you get by mixing blue and yellow?\tGreen\tOrange\tPurple\tBrown",
        "general\t2\t0\tWhich festival is known as the Festival of Lights in India?\tDiwali\tHoli\tEid\tNavratri",
        "general\t1\t0\tWhat is the tallest animal in the world?\tGiraffe\tElephant\tOstrich\tCamel",
        "general\t2\t0\tHow many strings does a standard violin have?\t4\t5\t6\t3",
        "general\t1\t0\tWhich vitamin are oranges famous for?\tVitamin C\tVitamin A\tVitamin D\tVitamin B12",
        "general\t2\t0\tWhich country gave the Statue of Liberty to the United States?\tFrance\tEngland\tSpain\tItaly",
        "general\t2\t0\tIn chess, which piece moves only diagonally?\tBishop\tRook\tKnight\tPawn",
        "general\t1\t0\tWhich animal is known as the king of the jungle?\tLion\tTiger\tElephant\tGorilla",
        "general\t2\t0\tWhat is the smallest unit of a digital image called?\tPixel\tByte\tVector\tFrame",
        "general\t3\t0\tHow many sides does a standard stop sign have?\t8\t6\t5\t10",
        "general\t1\t0\tHow many days are there in a week?\t7\t5\t6\t8",
        "kenya\t1\t0\tWhat is the capital city of Kenya?\tNairobi\tMombasa\tKisumu\tNakuru",
        "kenya\t1\t0\tWhat is the highest mountain in Kenya?\tMount Kenya\tMount Elgon\tMount Longonot\tMount Kulal",
        "kenya\t2\t0\tWhich lake, the largest in Africa, does Kenya share with Uganda and Tanzania?\tLake Victoria\tLake Turkana\tLake Naivasha\tLake Baringo",
        "kenya\t2\t0\tIn which year did Kenya gain independence?\t1963\t1960\t1970\t1958",
        "kenya\t1\t0\tWho was the first President of Kenya?\tJomo Kenyatta\tDaniel arap Moi\tMwai Kibaki\tTom Mboya",
        "kenya\t2\t0\tWhat does the national motto \"Harambee\" mean?\tLet us all pull together\tPeace and unity\tFreedom and work\tWelcome home",
        "kenya\t1\t0\tWhich Kenyan reserve is famous for the annual wildebeest migration?\tMaasai Mara\tAmboseli\tTsavo East\tSamburu",
        "kenya\t1\t0\tWhich port city is Kenya's largest on the Indian Ocean coast?\tMombasa\tMalindi\tLamu\tKilifi",
        "kenya\t1\t0\tWhat is the currency of Kenya?\tKenyan shilling\tKenyan dollar\tKenyan pound\tKenyan rand",
        "kenya\t2\t0\tWhich Kenyan won the Nobel Peace Prize in 2004?\tWangari Maathai\tLupita Nyong'o\tGrace Ogot\tJulie Gichuru",
        "kenya\t2\t0\tWhich Kenyan marathon runner ran a sub-two-hour marathon in an unofficial 2019 event?\tEliud Kipchoge\tDavid Rudisha\tPaul Tergat\tKipchoge Keino",
        "kenya\t1\t0\tWhat is the Swahili word for \"thank you\"?\tAsante\tKaribu\tPole\tSawa",
        "kenya\t1\t0\tWhich mobile money service did Safaricom launch in 2007?\tM-Pesa\tAirtel Money\tT-Kash\tEquitel",
        "kenya\t2\t0\tWhich colours appear on the Kenyan flag?\tBlack, red, green and white\tRed, white and blue\tGreen, yellow and red\tBlue, white and gold",
        "kenya\t1\t0\tWhich two languages are Kenya's official languages?\tEnglish and Swahili\tEnglish and French\tSwahili and Arabic\tSwahili and Kikuyu",
        "kenya\t2\t0\tWhich imaginary line crosses Kenya near Nanyuki?\tThe Equator\tThe Tropic of Cancer\tThe Prime Meridian\tThe Tropic of Capricorn",
        "kenya\t2\t0\tWhich Rift Valley lake is famous for its flamingos?\tLake Nakuru\tLake Victoria\tLake Turkana\tLake Jipe",
        "kenya\t2\t0\tWhat is the Swahili word for \"friend\"?\tRafiki\tMama\tBaba\tSafari",
        "kenya\t3\t0\tIn which year was Kenya's current constitution promulgated?\t2010\t2002\t1992\t2013",
        "kenya\t3\t0\tWhich Kenyan town is nicknamed the \"Home of Champions\" for its runners?\tIten\tKisii\tEmbu\tVoi",
        "kenya\t2\t0\tWhich of these animals is NOT one of the \"Big Five\"?\tGiraffe\tLion\tLeopard\tRhinoceros",
        "tech\t1\t0\tWhat does CPU stand for?\tCentral Processing Unit\tComputer Personal Unit\tCentral Program Utility\tCore Power Unit",
        "tech\t1\t0\tWhat does \"www\" stand for in a web address?\tWorld Wide Web\tWide World Web\tWeb World Wire\tWorld Web Window",
        "tech\t1\t0\tAndroid is an operating system developed by which company?\tGoogle\tApple\tMicrosoft\tSamsung",
        "tech\t2\t0\tWhat does HTML stand for?\tHyperText Markup Language\tHigh Text Machine Language\tHyperTool Multi Language\tHome Text Markup Level",
        "tech\t3\t0\tWhat is the decimal number 5 written in binary?\t101\t110\t011\t111",
        "tech\t2\t0\tWhat does USB stand for?\tUniversal Serial Bus\tUnited System Board\tUniversal Signal Box\tUnified Serial Band",
        "tech\t1\t0\tWhich of these is a programming language?\tPython\tPhotoshop\tChrome\tRouter",
        "tech\t1\t0\tHow many bits are there in a byte?\t8\t4\t16\t10",
        "tech\t2\t0\tWhat does RAM stand for?\tRandom Access Memory\tRead Access Memory\tRapid Active Memory\tRun All Memory",
        "tech\t1\t0\tWhat does AI stand for?\tArtificial Intelligence\tAutomatic Internet\tAdvanced Input\tApplied Interface",
        "tech\t2\t0\tWhat does SMS stand for?\tShort Message Service\tSimple Mobile Signal\tSmart Message System\tSend My Sound",
        "tech\t2\t0\tWhat does URL stand for?\tUniform Resource Locator\tUniversal Remote Link\tUnified Route Language\tUser Reference Label",
        "tech\t2\t0\tWhat does PDF stand for?\tPortable Document Format\tPrinted Data File\tPersonal Document Folder\tPublic Display Format",
        "tech\t1\t0\tWhich technology uses satellites to work out your location?\tGPS\tBluetooth\tNFC\tHDMI",
        "tech\t2\t0\tWhat is \"phishing\"?\tTricking people into giving away private information\tCatching fish online\tSpeeding up a network\tBacking up files",
        "tech\t3\t0\tWhat does HTTP stand for?\tHyperText Transfer Protocol\tHigh Transfer Text Process\tHyperTool Transmission Path\tHome Transfer Text Protocol",
        "tech\t1\t0\tWho co-founded Microsoft with Paul Allen?\tBill Gates\tSteve Jobs\tElon Musk\tMark Zuckerberg",
        "tech\t2\t0\tWhat does LAN stand for?\tLocal Area Network\tLarge Access Node\tLinked Active Network\tLong Area Net",
        "tech\t3\t0\tWhich was the first widely used graphical web browser, released in 1993?\tMosaic\tChrome\tFirefox\tSafari",
        "tech\t1\t0\tWhich keyboard shortcut copies selected text on most computers?\tCtrl + C\tCtrl + V\tCtrl + X\tCtrl + Z",
    };

    /** root \t letters \t words(comma) \t placed(word:row:col:A|D;...) \t height \t width */
    public static final String[] WORDS = {
        "PEOPLE\teelopp\tEEL,ELOPE,LEE,LOPE,PEE,PEEL,PEEP,PEOPLE,PEP,PLOP,POLE,POP,POPE\tPEOPLE:2:3:A;ELOPE:2:0:A;PEEP:2:3:D;PLOP:2:6:D;PEEL:5:3:D;LOPE:2:1:A;POPE:0:3:D;POLE:5:6:A;EEL:6:3:D;PEE:2:3:D;POP:0:3:D;PEP:5:3:A;LEE:2:7:A\t9\t10",
        "PUBLIC\tbcilpu\tBLIP,CLIP,CLUB,CUB,CUP,LIB,LIP,PUB,PUBIC,PUBLIC\tPUBLIC:0:0:A;PUBIC:0:0:D;CLIP:0:5:A;CLUB:0:5:D;BLIP:0:2:D;CUB:4:0:A;LIP:0:6:A;LIB:0:3:D;CUP:4:0:D;PUB:0:0:A\t7\t9",
        "SCHOOL\tchloos\tCOLS,COO,COOL,COOLS,COOS,SCHOOL,SHOO,SOLO\tSCHOOL:0:2:A;COOLS:0:3:D;SOLO:0:2:D;COOL:0:3:D;SHOO:1:0:A;COLS:3:1:A;COOS:3:1:D;COO:0:3:D\t7\t8",
        "CENTER\tceenrt\tCENT,CENTER,ENTER,ERE,ERECT,NET,RENT,TEE,TEEN,TEN,TREE\tCENTER:0:0:A;ENTER:0:1:A;ERECT:0:4:A;TEEN:0:3:D;CENT:0:0:A;RENT:0:5:D;TREE:0:8:D;TEE:0:3:D;NET:3:3:A;TEN:3:5:A;ERE:0:4:A\t4\t9",
        "MEMBER\tbeemmr\tBEE,BEER,EMBER,ERE,MEMBER,MEME,MERE\tMEMBER:0:2:A;EMBER:0:3:A;MEME:0:0:A;BEER:0:5:D;MERE:0:2:D;BEE:0:5:D;ERE:1:2:D\t4\t8",
        "OFFICE\tceffio\tFIE,FIEF,FIFE,FOE,ICE,OFF,OFFICE\tOFFICE:0:0:A;FIFE:0:1:D;FIEF:0:2:D;FIE:0:2:D;OFF:0:0:A;ICE:0:3:A;FOE:3:2:A\t4\t6",
        "WITHIN\thiintw\tHINT,HIT,NIT,THIN,TIN,TWIN,WHIT,WIN,WIT,WITH,WITHIN\tWITHIN:0:0:A;WHIT:0:0:D;THIN:0:2:A;WITH:0:0:A;HINT:0:3:A;TWIN:0:2:D;HIT:1:0:D;WIN:1:2:D;NIT:0:5:D;WIT:0:0:A;TIN:3:0:A\t4\t7",
        "ACCESS\taccess\tACCESS,ACE,ACES,ASS,CASE,CASES,SACS,SEA,SEAS,SECS\tACCESS:0:0:A;CASES:0:1:D;SEAS:0:4:D;SACS:0:5:A;CASE:0:1:D;ACES:0:0:D;SECS:3:0:A;ASS:2:4:D;SEA:0:4:D;ACE:0:0:D\t5\t9",
        "CHANGE\taceghn\tACE,ACHE,ACNE,AGE,CAGE,CAN,CANE,CHANGE,EACH,HAG,HANG,HEN,NAG\tCHANGE:3:0:A;ACHE:3:2:D;HANG:3:1:A;CAGE:3:0:D;ACNE:4:1:A;CANE:0:5:D;EACH:2:2:D;HEN:5:2:D;CAN:0:5:D;HAG:3:1:D;NAG:4:3:D;ACE:1:5:A;AGE:4:0:D\t8\t8",
        "QUALITY\tailqtuy\tAIL,ALT,LAT,LAY,LIT,QUA,QUAIL,QUALITY,QUAY,QUILT,QUIT,TAIL\tQUALITY:1:1:A;QUAIL:1:1:D;QUILT:0:2:D;QUAY:0:2:A;TAIL:1:6:D;QUIT:2:0:A;LIT:1:4:A;QUA:1:1:A;AIL:3:1:D;LAY:1:4:D;LAT:5:1:A;ALT:3:1:A\t6\t8",
        "BETTER\tbeertt\tBEE,BEER,BEET,BERET,BET,BETTER,ERE,TEE,TREE\tBETTER:1:1:A;BERET:1:1:D;BEET:0:2:D;BEER:2:0:A;TREE:1:3:D;TEE:3:2:A;BEE:0:2:D;BET:1:1:A;ERE:2:1:D\t6\t7",
        "MEMORY\temmory\tEMO,MEMO,MEMORY,MOM,MORE,ORE,ROE,RYE,YORE\tMEMORY:0:0:A;MEMO:0:0:A;YORE:0:5:A;MORE:0:0:D;EMO:0:1:A;ROE:0:4:D;ORE:0:6:A;RYE:0:7:D;MOM:0:2:D\t4\t9",
        "AUGUST\tagstuu\tAUGUST,GAS,GUST,GUT,GUTS,SAG,SAT,STAG,TAG,TAGS,TUG,TUGS\tAUGUST:0:0:A;TUGS:0:5:A;STAG:0:4:D;TAGS:1:4:D;GUTS:0:2:D;GUST:0:2:A;SAT:0:8:D;GUT:0:2:D;TAG:1:4:D;TUG:0:5:A;GAS:0:7:D;SAG:3:2:A\t5\t9",
        "STATUS\tassttu\tASS,ASST,SAT,STAT,STATS,STATUS,TAT,TATS,TAUT\tSTATUS:0:2:A;STATS:0:2:D;TAUT:0:3:D;TATS:1:2:D;ASST:0:0:A;STAT:0:2:A;SAT:0:7:A;ASS:0:0:A;TAT:0:3:A\t5\t10",
        "FUTURE\tefrtuu\tFER,FRET,FUR,FUTURE,REF,RUE,RUT,TRUE,TURF\tFUTURE:0:0:A;TURF:0:2:D;FRET:0:0:D;TRUE:3:0:D;RUE:4:0:D;FER:3:2:A;REF:0:4:A;RUT:0:4:D;FUR:3:2:D\t7\t7",
        "BECOME\tbceemo\tBECOME,BEE,COB,COMB,COME,EMO,MOB\tBECOME:1:0:A;COMB:1:2:D;COME:1:2:A;COB:0:3:D;EMO:1:1:D;MOB:2:1:A;BEE:1:0:D\t5\t6",
        "ENERGY\teegnry\tEERY,ENERGY,ERE,ERG,EYE,GEE,GENE,GENRE,GREEN,GREY,RYE,YEN\tENERGY:1:3:A;GREEN:1:0:A;GENRE:1:7:D;GENE:1:0:D;GREY:0:6:D;EERY:2:6:A;EYE:2:6:D;RYE:2:8:A;ERG:1:5:A;YEN:3:6:D;GEE:2:5:A;ERE:4:6:A\t6\t11",
        "JOURNAL\tajlnoru\tJAR,JOURNAL,LOAN,LORN,LUNAR,NOR,OAR,ORAL,OUR,RAN,ROAN,RUN,ULNA,URN\tJOURNAL:1:0:A;LUNAR:1:6:D;ROAN:1:3:D;LOAN:1:6:A;ORAL:1:1:D;LORN:4:1:D;ULNA:1:2:D;NOR:0:1:D;OAR:2:3:A;URN:1:2:A;RAN:3:0:A;OUR:1:1:A;RUN:2:5:A;JAR:1:0:D\t8\t10",
        "HAVING\taghinv\tANI,AVG,GAIN,GIN,HAG,HANG,HAVING,HING,NAG,NIGH,VAIN,VAN,VIA\tHAVING:1:0:A;GAIN:1:5:A;HANG:1:0:D;HING:0:3:D;NIGH:1:4:D;VAIN:1:2:D;GIN:4:0:A;HAG:0:3:A;VAN:2:1:A;NAG:1:8:D;VIA:0:7:D;ANI:2:2:A;AVG:1:1:D\t5\t9",
        "COMMON\tcmmnoo\tCOMM,COMMON,CON,COO,COON,MOM,MONO,MOO,MOON\tCOMMON:1:0:A;COON:1:0:D;MONO:1:3:A;COMM:1:0:A;MOON:1:2:D;MOO:1:2:D;MOM:1:3:D;CON:0:1:D;COO:1:0:D\t5\t7",
        "LIVING\tgiilnv\tGIN,LII,LIVING,LVI,LVII,NIL,VIGIL,VII\tLIVING:0:0:A;VIGIL:0:2:D;LVII:0:0:D;GIN:0:5:A;NIL:0:4:D;LII:4:2:A;VII:1:0:D;LVI:0:0:D\t5\t8",
        "USUALLY\tallsuuy\tALL,ALLY,LAY,LAYS,LUAU,LUAUS,SALLY,SAY,SLAY,SLY,SULLY,USUAL,USUALLY\tUSUALLY:1:3:A;USUAL:1:3:A;SALLY:1:4:D;SULLY:0:3:D;LUAUS:1:0:A;ALLY:1:6:A;SLAY:2:2:A;LUAU:1:0:A;LAYS:2:3:A;LAY:2:3:A;ALL:1:6:A;SAY:0:3:A;SLY:2:2:D\t6\t10",
        "LYRICS\tcilrsy\tCIS,CRY,ICY,LYRIC,LYRICS,SIC,SIR,SLY,YRS\tLYRICS:1:1:A;LYRIC:1:1:A;CIS:1:5:D;CRY:0:3:D;ICY:1:4:D;SLY:1:0:A;SIC:0:4:D;SIR:1:6:A;YRS:1:2:D\t4\t9",
        "CHOOSE\tcehoos\tCHOOSE,CHOSE,COO,COOS,ECHO,ECHOS,HES,HOE,HOES,HOSE,SHE,SHOE,SHOO\tCHOOSE:0:0:A;ECHOS:0:5:A;CHOSE:0:0:D;SHOE:0:4:D;ECHO:0:5:A;HOSE:1:0:D;SHOO:0:9:D;HOES:1:4:D;COOS:0:6:D;SHE:3:0:A;HOE:1:4:D;HES:3:1:A;COO:0:6:D\t5\t10",
        "RECEIVE\tceeeirv\tEERIE,ERE,EVE,EVER,ICE,IRE,RECEIVE,REEVE,REV,RICE,VEER,VICE,VIE\tRECEIVE:1:0:A;REEVE:1:0:D;EERIE:1:1:D;VICE:4:0:A;VEER:0:1:D;RICE:3:1:A;EVER:3:0:D;REV:6:0:A;IRE:1:4:D;VIE:1:5:D;ICE:4:1:A;EVE:3:0:D;ERE:5:0:D\t8\t7",
        "GOOGLE\teggloo\tEGG,EGO,GEL,GOO,GOOGLE,LEG,LOG,LOGE,LOGO,OGLE,OLEO\tGOOGLE:0:2:A;LOGE:0:6:D;LOGO:0:0:A;OGLE:0:4:A;OLEO:0:3:D;LOG:0:6:D;LEG:0:6:A;GEL:2:6:D;GOO:0:2:A;EGG:0:7:A;EGO:0:7:D\t5\t10",
        "HIGHER\teghhir\tERG,HEIR,HER,HIE,HIGH,HIGHER,HIRE,IRE,REHI,RIG\tHIGHER:1:2:A;HEIR:1:2:D;REHI:1:0:A;HIRE:1:5:D;HIGH:1:2:A;IRE:2:5:D;ERG:1:6:A;RIG:1:7:D;HER:1:5:A;HIE:0:3:D\t5\t9",
        "EFFECTS\tceeffst\tEFFECT,EFFECTS,EST,FECES,FEE,FEES,FEET,FEST,SECT,SEE,SET,TEE,TEES\tEFFECTS:1:0:A;EFFECT:1:0:A;FECES:1:1:D;FEES:1:2:D;FEET:2:0:A;FEST:4:0:A;SECT:1:6:A;TEES:1:5:D;FEE:1:2:D;TEE:1:5:D;SET:0:3:D;EST:4:1:A;SEE:1:6:D\t6\t10",
        "REMEMBER\tbeeemmrr\tBEE,BEER,BRR,EMBER,ERE,ERR,MEMBER,MEME,MERE,REMEMBER\tREMEMBER:1:0:A;MEMBER:1:2:A;EMBER:1:3:A;MEME:1:2:D;BEER:1:5:D;MERE:3:2:A;BRR:0:0:D;ERR:1:6:A;BEE:1:5:D;ERE:3:3:A\t5\t9",
        "YELLOW\tellowy\tELL,LOW,LOWLY,LYE,OWE,OWL,WELL,WOE,YELL,YELLOW,YEW,YOWL\tYELLOW:1:0:A;LOWLY:1:3:A;YELL:1:0:A;WELL:1:5:D;YOWL:1:0:D;OWL:1:4:A;OWE:0:5:D;LYE:1:6:A;WOE:3:0:A;YEW:1:7:A;LOW:1:3:A;ELL:1:1:A\t5\t10",
        "FRENCH\tcefhnr\tCHEF,FEN,FER,FERN,FRENCH,HEN,HER,REF\tFRENCH:1:0:A;FERN:1:0:D;CHEF:1:4:A;HEN:1:5:D;FER:1:0:D;REF:1:1:D;HER:0:2:D;FEN:1:7:A\t5\t10",
        "ENGINE\teeginn\tENGINE,GEE,GENE,GENIE,GIN,INN,NINE\tENGINE:1:0:A;GENIE:1:2:D;GENE:0:0:D;NINE:1:1:D;GIN:1:2:A;INN:1:3:D;GEE:0:0:A\t6\t6",
        "SCREEN\tceenrs\tERE,SCENE,SCREEN,SEE,SEEN,SEER,SERE,SNEER\tSCREEN:2:1:A;SNEER:2:1:D;SCENE:1:2:D;SEEN:5:0:A;SEER:1:2:A;SERE:0:3:D;SEE:1:2:A;ERE:1:3:D\t7\t7",
        "VOLUME\telmouv\tELM,EMO,EMU,LOVE,MOLE,MOVE,MULE,OVULE,OVUM,VOL,VOLE,VOLUME\tVOLUME:2:1:A;OVULE:2:2:D;MULE:2:5:D;LOVE:5:2:A;OVUM:5:3:D;VOLE:2:1:D;MOVE:3:0:A;MOLE:0:3:D;EMO:3:3:D;EMU:3:3:A;ELM:2:6:A;VOL:2:1:A\t9\t9",
        "COMING\tcgimno\tCOG,COIN,COMING,CON,GIN,ICON,INC,ION,MIN\tCOMING:0:0:A;COIN:0:0:D;ICON:0:3:D;MIN:0:2:A;GIN:0:5:A;COG:1:3:A;INC:2:0:D;ION:2:0:A;CON:1:3:D\t5\t8",
        "OBJECT\tbcejot\tBET,BOT,COB,COT,COTE,JET,JOB,JOT,OBJ,OBJECT,TOE\tOBJECT:1:1:A;COTE:1:5:D;COB:1:0:A;JOT:1:3:D;BOT:1:2:D;COT:1:5:D;JOB:0:1:D;BET:2:1:D;TOE:1:6:A;JET:3:0:A;OBJ:1:1:A\t5\t9",
        "FOLLOW\tflloow\tFLOW,FOLLOW,FOO,FOOL,FOWL,LOW,OWL,WOLF,WOO,WOOF,WOOL\tFOLLOW:1:1:A;FOWL:1:1:D;WOOF:1:6:A;FLOW:1:9:D;FOOL:0:2:D;WOOL:2:0:A;WOLF:1:6:D;FOO:0:2:D;OWL:2:1:D;WOO:1:6:A;LOW:1:4:A\t5\t10",
        "CHOICE\tccehio\tCHI,CHIC,CHOICE,ECHO,HIE,HOE,ICE\tCHOICE:0:1:A;ECHO:0:0:A;CHIC:0:1:D;CHI:0:1:D;HOE:0:2:D;HIE:2:0:A;ICE:0:4:A\t4\t7",
        "LEVELS\teellsv\tEEL,EELS,ELL,ELLS,ELSE,ELVES,EVE,EVES,LEE,LEES,LEVEL,LEVELS,SEE,SELL\tLEVELS:0:0:A;LEVEL:0:0:A;ELVES:0:1:D;EELS:0:3:D;SELL:0:5:A;ELLS:0:6:A;ELSE:0:3:A;EVES:1:3:A;LEES:3:0:A;EEL:0:3:D;LEE:3:0:A;EVE:0:1:A;ELL:0:6:A;SEE:0:5:D\t5\t10",
        "LETTER\teelrtt\tEEL,ERE,LEE,LEER,LET,LETTER,REEL,TEE,TEL,TREE\tLETTER:1:0:A;REEL:1:5:A;LEER:1:0:D;TREE:1:2:D;EEL:1:6:A;TEE:1:3:D;TEL:0:1:D;LEE:1:0:D;LET:1:0:A;ERE:1:4:A\t5\t9",
        "DEGREE\tdeeegr\tDEER,DEGREE,EDGE,EDGER,ERE,ERG,GEE,GEED,GREED,RED,REED\tDEGREE:2:0:A;EDGER:2:1:D;GREED:2:2:A;EDGE:2:1:D;DEER:2:0:D;REED:2:3:A;GEED:0:1:D;RED:5:0:A;ERG:5:1:D;GEE:0:1:D;ERE:4:0:D\t8\t7",
        "SURVEY\tersuvy\tREV,REVS,RUE,RUES,RUSE,RYE,SUE,SURE,SURVEY,USE,USER,VERY,YES,YRS\tSURVEY:2:0:A;VERY:2:3:D;REVS:2:2:D;SURE:0:2:D;RUSE:4:3:A;RUES:1:1:D;USER:4:4:A;SUE:2:0:D;USE:4:4:A;RUE:1:1:D;YES:2:5:D;YRS:2:5:A;RYE:4:3:D;REV:2:2:D\t7\t8",
        "CLASSIC\taccilss\tAIL,AILS,ASS,CAL,CIS,CLASS,CLASSIC,LASS,SACS,SAIL,SAILS,SIC,SICS,SISAL\tCLASSIC:0:0:A;CLASS:0:0:A;SISAL:0:3:D;SAILS:0:4:D;SACS:4:4:A;LASS:0:1:A;SICS:0:4:A;AILS:1:4:D;SAIL:0:4:D;CIS:0:0:D;AIL:1:4:D;ASS:0:2:A;SIC:0:4:A;CAL:3:2:A\t5\t8",
        "SUCCESS\tccesssu\tCUE,CUES,CUSS,CUSSES,SECS,SUCCESS,SUE,SUES,USE,USES\tSUCCESS:0:1:A;CUSSES:0:3:D;SUES:0:1:D;CUSS:0:3:D;SECS:2:0:A;CUES:0:4:D;USES:3:0:A;SUE:0:1:D;USE:3:0:A;CUE:0:4:D\t6\t8",
        "MAXIMUM\taimmmux\tAIM,IMAM,MAIM,MAX,MAXIM,MAXIMUM,MIX,MUM\tMAXIMUM:2:0:A;MAXIM:2:0:A;IMAM:2:3:D;MAIM:0:3:D;MUM:2:4:A;MAX:2:0:A;MIX:2:0:D;AIM:1:3:D\t6\t7",
    };
}
