name: Deploy UniConnect to Firebase Hosting

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi

    - name: Verify Firebase Config
      run: |
        echo "Verifying Firebase configuration for UniConnect..."
        if [ -f firebase.js ]; then
          echo "✓ firebase.js found"
        else
          echo "✗ firebase.js missing"
          exit 1
        fi

    - name: Deploy to Firebase
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UNICONNECT }}'
        channelId: live
        projectId: 'uniconnect-ee95c'
        entryPoint: './'
        
    - name: Deploy to Preview Channel
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_UNICONNECT }}'
        channelId: preview-${{ github.head_ref || github.ref_name }}
        projectId: 'uniconnect-ee95c'
        entryPoint: './'