/* existing notification stabilization layer: safe DM preview hardening */
(function(){'use strict';
if(window.__NotificationStabilizationLayer)return;
const DEDUP_WINDOW_MS=5000,MAX_STORM_PER_WINDOW=8,STORM_WINDOW_MS=3000;
function encrypted(v){if(typeof v!=='string')return true;const s=v.trim();if(!s)return false;if(/^(encrypted message|decryption failed|unable to decrypt)$/i.test(s))return true;if(/^(v\d+:|x3dh:|e2e:|ciphertext:)/i.test(s))return true;if(s.length>180&&/^[A-Za-z0-9+/_=-]+$/.test(s))return true;if((s[0]==='{'&&s.at(-1)==='}')||(s[0]==='['&&s.at(-1)===']')){try{const o=JSON.parse(s);if(o&&(o.ciphertext||o.cipher||o.encrypted||o.iv||o.ephemeralKey||o.x3dh))return true}catch(_){}}return false}
function preview(body,message){try{const p=window.KynectaE2E?.peekDecryptedText?.(message);if(typeof p==='string'&&p.trim()&&!encrypted(p))return p.trim().slice(0,240)}catch(_){}return typeof body==='string'&&!encrypted(body)?body.trim().slice(0,240):'New message received'}
class Dedup{constructor(){this.m=new Map()}dup(k){const n=Date.now(),p=this.m.get(k);if(p&&n-p<DEDUP_WINDOW_MS)return true;this.m.set(k,n);for(const[x,t]of this.m)if(n-t>10000)this.m.delete(x);return false}}
class Storm{constructor(){this.a=[];this.s=0}allow(){const n=Date.now();this.a=this.a.filter(t=>n-t<STORM_WINDOW_MS);if(this.a.length>=MAX_STORM_PER_WINDOW){this.s++;return false}this.a.push(n);return true}}
class Unread{constructor(){this.m=new Map;this.total=0}set(c,n){if((this.m.get(c)||0)===n)return;this.m.set(c,Math.max(0,n));this.total=[...this.m.values()].reduce((a,b)=>a+b,0)}inc(c,n=1){this.set(c,(this.m.get(c)||0)+n)}clear(c){this.set(c,0)}}
class Layer{constructor(){this.d=new Dedup;this.s=new Storm;this.u=new Unread;this.pending=[];this.reconnect=0}
init(){this.socket();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')this.flush()});this.patchNotification();this.bannerBridge();window.__NotificationStabilizationLayer=this;window.NotifStab=this}
shouldShow(id,chat){return !this.d.dup(`${chat}:${id}`)&&this.s.allow()}
notifyApp(title,body,o={}){const module=o.module||'app',context=o.contextId||module;let b=(module==='dm'||module==='message')?preview(body,o.message):typeof body==='string'?body.slice(0,240):'';let t=(module==='dm'||module==='message')&&encrypted(String(body||''))?'New message':title;if(!this.shouldShow(`${t}:${b}`,context))return;if(window.top!==window.self){try{window.top.postMessage({type:'KYN_APP_BANNER',title:t,body:b,module,contextId:o.contextId,icon:o.icon},'*')}catch(_){}}else this.render(t,b,o)}
bannerBridge(){window.addEventListener('message',e=>{const d=e.data;if(!d||d.type!=='KYN_APP_BANNER'||window.top!==window.self)return;const m=d.module||'app',b=(m==='dm'||m==='message')?preview(d.body,d.message):typeof d.body==='string'?d.body.slice(0,240):'',t=(m==='dm'||m==='message')&&encrypted(String(d.body||''))?'New message':d.title;if(!this.shouldShow(`${t}:${b}`,d.contextId||m))return;this.render(t,b,d)})}
render(title,body,o={}){if(!this.el){const st=document.createElement('style');st.textContent='#kyn-app-banner{position:fixed;top:-80px;left:50%;transform:translateX(-50%);z-index:2147483000;min-width:280px;max-width:420px;background:rgba(28,28,34,.96);color:#fff;border-radius:14px;padding:12px 16px;display:flex;gap:10px;font-family:inherit;transition:top .28s ease}#kyn-app-banner.kyn-app-banner-visible{top:14px}';document.head.appendChild(st);this.el=document.createElement('div');this.el.id='kyn-app-banner';this.el.innerHTML='<span class="i"></span><div><p class="t"></p><p class="b"></p></div>';document.body.appendChild(this.el)}this.el.querySelector('.i').textContent=o.icon||({dm:'💬',friend:'👥',call:'📞',marketplace:'🛍️'}[o.module]||'🔔');this.el.querySelector('.t').textContent=title||'';this.el.querySelector('.b').textContent=body||'';requestAnimationFrame(()=>this.el.classList.add('kyn-app-banner-visible'));clearTimeout(this.timer);this.timer=setTimeout(()=>this.el.classList.remove('kyn-app-banner-visible'),4500)}
socket(){const h=(type,p)=>{if(type==='socket:connected'||type==='socket:reconnected'){this.reconnect=Date.now();return}if(!['message:created','new_message','MESSAGE_RECEIVED'].includes(type))return;const c=p?.chatId||p?.conversationId||'global',id=p?.id||p?.messageId||p?.localId;if(Date.now()-this.reconnect<2000||!this.shouldShow(id,c))return;if(document.visibilityState==='hidden'){this.pending.push({p});if(this.pending.length>20)this.pending.shift();return}if(p?.senderId!==this.me())this.u.inc(c)};const bus=window.KynectaEventBus||window.appEvents;if(bus)bus.on('SOCKET_EVENT',p=>{if(p?.type)h(p.type,p)});window.addEventListener('message',e=>{if(e.data?.type)h(e.data.type,e.data)})}
flush(){const x=this.pending.splice(0),m={};for(const{p}of x){const c=p?.chatId||p?.conversationId||'global';m[c]=(m[c]||0)+1}for(const[c,n]of Object.entries(m))this.u.inc(c,n)}
me(){try{return JSON.parse(localStorage.getItem('kynecta_auth')||localStorage.getItem('nexipa_auth')||'{}')?.user?.id||null}catch(_){return null}}
patchNotification(){if(typeof Notification==='undefined')return;const O=window.Notification,self=this;window.Notification=function(title,opt={}){const b=preview(opt.body,opt.message),t=encrypted(String(opt.body||''))?'New message':title,k=`${t}|${opt.tag||''}|${b.slice(0,30)}`;if(self.d.dup(k)||!self.s.allow())return{close(){}};return new O(t,{...opt,body:b})};Object.assign(window.Notification,O);Object.setPrototypeOf(window.Notification,O)} }
new Layer().init();console.log('[NotifStab] safe notification layer ready');
})();